### ISSUE TITLE
(Feature Request) Central place for users to report journal site compatibility?

### ISSUE THREAD

**Issue by keiichiiownsu12** [JabRef/JabRef-Browser-Extension#104]
Hello,

Somewhat of a feature request. I noticed the plugin works well for some journal sites (e.g. Elsevier/Science Direct) but not for others (e.g. Springerlink or lesser-known journals).

I was curious if there is or if there could be a dedicated thread, wiki page, or markdown doc where users can report on compatibility for specific journal websites? Could potentially be very informative for both users and developers.

**Comment by tobiasdiez** [comment]
If a website does not work, then it is probably a bug in the code of this extension, and hence should be reported as a separate bug report (with the error message that you get in the browser extension).

In case the parsing works in principle but has some shortcomings, then it should be reported at https://github.com/zotero/translators.
