### ISSUE TITLE
Not proceeding beyond "Send to JabRef…"  – JabRef 4.3.1, FreeBSD

### ISSUE THREAD

**Issue by grahamperrin** [JabRef/JabRef-Browser-Extension#107]
I get this far: 

![image](https://user-images.githubusercontent.com/192271/70434202-7c7ba900-1a7b-11ea-9873-115fde7d631a.png)

– but a click on **Send to JabRef…** seems to have no effect; the pop-up remains on screen. 

```text
$ date ; uname -v 
Mon  9 Dec 2019 12:00:59 GMT
FreeBSD 13.0-CURRENT #45 r355536: Mon Dec  9 03:20:46 GMT 2019     root@momh167-gjp4-8570p:/usr/obj/usr/src/amd64.amd64/sys/GENERIC-NODEBUG 
$ pkg query '%o %v %R' firefox jabref python2 python3
www/firefox 71.0_2,1 FreeBSD
print/jabref 4.3.1,1 FreeBSD
lang/python2 2_3 FreeBSD
lang/python3 3_3 FreeBSD
$ 
```

– consistent with the 4.3.1 that's currently seen at <https://www.fosshub.com/JabRef.html>.

https://www.freshports.org/print/jabref/

I see #99 (closed) and <https://github.com/JabRef/JabRef-Browser-Extension/issues/59#issuecomment-546411384>

> … from my experience it is more stable with 5.0 (dev).

**Comment by tobiasdiez** [comment]
Are there any errors shown in the Browser Console?

And yes, Linux support is in general more stable with the latest dev version https://builds.jabref.org/master/

**Comment by grahamperrin** [comment]
Firefox 71.0: 

`No such native application org.jabref.jabref` `NativeMessaging.jsm:112`

`    startupPromise resource://gre/modules/NativeMessaging.jsm:112`

**Comment by tobiasdiez** [comment]
Ok, this says that Firefox is not able to find JabRef, which means that the `org.jabref.jabref.json` file is not in the correct location. Did you followed the instructions under https://github.com/JabRef/JabRef-Browser-Extension#linux ?
