### ISSUE TITLE
Communication Error & Missing Icon (Linux Alpha RPM, FF)

### ISSUE THREAD

**Issue by PorcelainMouse** [JabRef/JabRef-Browser-Extension#110]
I'm super excited about this extension.  Thanks!

I have read through many open and closed bug reports and I'm still pretty confused.  Seems like it is supposed to be working, but I'm not sure.  I still have problems that other people have reported and are already closed.

1. In Firefox, in the JabFox preferences, I see "Error: Attempt to postMessage on disconnected port"
1. I cannot find the JabFox icon anywhere.

jabref-5.0.30001-1.x86_64
FF 70
jabfox 2.1.2 

Sounds like v5 is on the way?  Should I wait until then and see what happens?

**Comment by tobiasdiez** [comment]
Can you please verify that `org.jabref.jabref.json` is in the correct folder as described here: https://github.com/JabRef/JabRef-Browser-Extension#linux

Furthermore, do you get any error messages in the Browser Console (Ctrl + Shift + J) ?

**Comment by PorcelainMouse** [comment]
Ah, okay, no I did'nt follow that extra bit about org.jabref.jabref.json.  Let me try...

In the meantime, I don't see any obviously related errors, just this:
`[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIDOMWindowUtils.removeSheetUsingURIString]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/ExtensionCommon.jsm :: runSafeSyncWithoutClone :: line 75"  data: no]`

**Comment by PorcelainMouse** [comment]
Okay, I have the .jason file in my personal .mozilla/native-messaging-hosts/ directory, but no joy.

I now see many errors in the browser console, but still none that are obviously related to jabref.

**Comment by PorcelainMouse** [comment]
If check "show content messages" I see many references to JabFox, but none are errors.

**Comment by PorcelainMouse** [comment]
Oops, I forgot to have JabRef running for the last few tests.  Yes, I'm getting a connection now!  Just no icon.  The connection problem just have been the incomplete manual part of the Linux installation.  It's a little hard to see when that text is collapsed and I assumed that "if you didn't use .deb" you meant .deb or .rpm.  In any case, thanks & sorry for opening a new issue.

Ah, okay, now I see the jabref icon, too!  It's in with the pulldown menu in the URL field.  Didn't realize you could add stuff there.  Okay, I'm having some other problems now, but I think this issue was all my errors.

**Comment by tobiasdiez** [comment]
@LyzardKing could you maybe have a look why the rpm installation does not work as supposed (appearently)?

**Comment by LyzardKing** [comment]
@PorcelainMouse 
What was the original issue? Was the json file not created with the proper contents?

**Comment by PorcelainMouse** [comment]
I'm pretty sure I fixed the problem by installing .json file in my private .mozilla/  directory.  The RPM did not put a copy in /usr/lib/mozilla, though I don't know if it is supposed to do that.
