### ISSUE TITLE
When a list of references is shown, open dialogue with a list of the entries and checkboxes to select specific ones to import

### ISSUE THREAD

**Issue by systemoperator** [JabRef/JabRef-Browser-Extension#120]
If you e.g. load one of the following web pages

- https://ieeexplore.ieee.org/search/searchresult.jsp?newsearch=true&queryText=moocs
- https://scholar.google.at/scholar?hl=en&as_sdt=0%2C5&q=moocs&btnG=

then the Zotero translators show a dialogue which allows selecting specific entries to import. It would be great, if this worked for JabFox as well.

**Comment by tobiasdiez** [comment]
The strategy is to send all entries to JabRef and then the user can select the relevant entries in JabRef's import selection dialog.
