### ISSUE TITLE
Urldate is set to "CURRENT\_TIMESTAMP" or is set inconsistent for websites

### ISSUE THREAD

**Issue by systemoperator** [JabRef/JabRef-Browser-Extension#122]
When importing a 'common' website like [https://github.com/JabRef/JabRef-Browser-Extension/issues](url) (or for example news sites) the resulting reference entry in JabRef gets the value "CURRENT\\_TIMESTAMP" in the entry field "Urldate".

For e.g. Wikipedia entries, this does not happen. Creating a reference for [https://en.wikipedia.org/wiki/Onychopterella](url) results in "2020-01-21TZ". Is the "TZ" needed in this case? I think it should only be written if the time is also contained (example: 2020-01-21T00:54:54Z).

Creating a reference for [https://dl.acm.org/doi/abs/10.1145/3051457.3053993](url) results in "2020-01-19" for the entry field "Urldate", which is fine.

**Comment by tobiasdiez** [comment]
This should be fixed in the next release.
