### ISSUE TITLE
JabFox icon is not shown or vanishes in address bar if link gets opened in new tab in background

### ISSUE THREAD

**Issue by systemoperator** [JabRef/JabRef-Browser-Extension#124]
When I browse a website and I trigger opening a contained link in a new tab in the background and I simply wait until the newly opend tab is fully loaded (not switching to the new tab yet), then in the current tab the JabFox icon in the address bar vanishes and when switching to the newly opened (fully loaded) tab, no JabFox icon is shown in the address bar either.

In order to again show the JabFox icon in the address bar, the tab must be reloaded. This is necessary for the intial tab, from which a new tab was opened and for the newly opened tab as well.

OS: Ubuntu 16.04
Browser: Mozilla Firefox 72.0.1

Remark: If one immediately switches to the newly opened tab while it loads, then in both tabs the JabFox icon persists.

**Comment by tobiasdiez** [comment]
This should be fixed in the next release.
