### ISSUE TITLE
JabFox not activated on the following DOI

### ISSUE THREAD

**Issue by joelostblom** [JabRef/JabRef-Browser-Extension#129]
When navigating to this site https://doi.org/10.1634/stemcells.2008-0183, jabfox remains inactive in the address bar and cannot be used to retrieve bibliographic information from the site. The DOI works as expected for adding bib info from within JabRef.

**Comment by joelostblom** [comment]
These DOIs also don't trigger JabFox:
- https://doi.org/10.1016/j.actpsy.2011.08.005
- https://doi.org/10.1167/8.16.13

FWIW these do all work in the zotero connector extension so there seems not to be something inherently wrong with the webpages.

I'm on Firefox 72.0.2

**Comment by joelostblom** [comment]
Related (same?) issue https://github.com/JabRef/JabRef-Browser-Extension/issues/90

**Comment by LyzardKing** [comment]
There might be something else to import from the zotero src.
The error is: :` TLDS is not defined at moz-extension://96145178-9e47-4639-85eb-a5495cdf8d84/Zotero/messaging_inject.js:76`

**Comment by tobiasdiez** [comment]
This should be fixed in the next release.
