### ISSUE TITLE
FF 73, Catalina - Error: Attempt to postMessage on disconnected port

### ISSUE THREAD

**Issue by kastork** [JabRef/JabRef-Browser-Extension#136]
Hello,

After installing JabRef 4.3.1 using the installer, I then installed the JabRef addon from the Firefox Addons manager.

In the Addon preferences, the Connection Status is

`Error: Attempt to postMessage on disconnected port`

I've double checked that the Advanced option for `Listen for remote operation on port` is checked, and I left the default port value untouched (6050)

The JabRef icon does show in the address bar, but it hangs on the status message `Send to JabRef...`

I know there are several related issues, but they all seem to be for Linux -- I'm on macOS (Catalina).

**Comment by LyzardKing** [comment]
The addon works best with the latest 5.x releases of jabref...
Could you verify that with that version it works?
Also, to debug it you can open the devtools console before clicking on the jabref icon in firefox
to see the error message

**Comment by IstvanZachar** [comment]
I get the same error under: JabFox 2.1.2, Firefox 74.0, JabRef 5.0, Windows 7 Pro, 64 bit. The DevTools console error is as follows when I turn JabFox on and it cannot establish a connection:

    ExtensionError: No such native application org.jabref.jabref ExtensionUtils.jsm:56:5
    Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. background.js:63

And this is the error when trying to pull a bibliography from the web:

    ExtensionError: No such native application org.jabref.jabref ExtensionUtils.jsm:56:5
    Sync encountered an error - see about:sync-log for the log file. policies.js:1005
        resetFileLog resource://services-sync/policies.js:1005
        InterpretGeneratorResume self-hosted:1157
        AsyncFunctionNext self-hosted:696

Jabref is open and remote port for JabRef is open and set to the default 6050.
The same setup using Chrome and the appropriate JabFox addon for Chrome works as expected on the same machine.

**Comment by IstvanZachar** [comment]
@tobiasdiez What kind of further feedbeck would help in resolving the issue?

**Comment by tobiasdiez** [comment]
The installation was heavily improved in the last few releases of JabRef, so this should work now more reliable. Please try again with the latest development version.

@IstvanZachar this error says that Firefox cannot find JabRef. Please try to reinstall JabRef and if this doesn't work please follow the steps described in the user manual. https://docs.jabref.org/import-export/import/jabref-browser-extension.

If the error is still there, please let me know and I'll reopen this issue.
