### ISSUE TITLE
url not defined @proxy

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/JabRef-Browser-Extension#153]
Error
> url is not defined at moz-extension://0e2ffb6f-f4e6-4cba-8631-9f4c7eb772fe/Zotero/proxy.js:867

when importing e.g. https://www.osapublishing.org/optica/abstract.cfm?uri=optica-6-5-686

**Comment by LyzardKing** [comment]
I cannot reproduce.
In Firefox I can import this citation succesfully

**Comment by tobiasdiez** [comment]
Thanks for testing. I guess it comes from the fact that I'm behind a proxy right now (to gain access to journals from home).

**Comment by tobiasdiez** [comment]
Seems to work now.

**Comment by tobiasdiez** [comment]
Experienced this again at https://link-springer-com.tudelft.idm.oclc.org/article/10.1134/S1061920821010039. Seems to be coming from the "Library access" extension.

**Comment by LyzardKing** [comment]
This one I can't access without the proxy credentials..
If I go directly to the springer link (https://link.springer.com/article/10.1134%2FS1061920821010039) it works.
