### ISSUE TITLE
No data imported : send to jabref works, but open a new tab without data

### ISSUE THREAD

**Issue by yzgol** [JabRef/JabRef-Browser-Extension#165]
Firefox 75.0 / Ubuntu 19.10 / Jabref 5.0 via snap.

The Jabref extension seems to work : it says that it's been sent to jabref, and it has actually open a new tab in jabref. But no data inside.

I don't see any problem related to jabref on the browser console.
In fact, I don't know much about it, there's a few error messages, but no new error appears when I use the jabref extension. 

![Capture de 2020-04-21 20:47:44](https://user-images.githubusercontent.com/64099997/79902250-70ccc580-8411-11ea-878c-3ad8c408b484.png)

It seems to appear on all websites. At least, I tried : 
https://arxiv.org/abs/2004.09440
http://www.sudoc.fr/000042641
https://link.springer.com/chapter/10.1007/3-540-39799-X_31

Hope it'll help

P.S. : it looks a lot like #52 but I use Jabref 5.0 through snap so it shouldn't be a problem with Java (or did I get it wrong ?) + the jabref window does open + The add-on says "Communication to JabRef successful"

P.P.S. : 
For information, the pre-existing errors are : 
UpdateUtils.jsm:151
update.locale file doesn't exist in either the application or GRE directories 
    getLocale resource://gre/modules/UpdateUtils.jsm:151
    AsyncFunctionThrow self-hosted:699

network-response-listener.js:84
NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIInterfaceRequestor.getInterface]

**Comment by LyzardKing** [comment]
It's actually related to an issue discussed in the gitter instance with @Siedlerchr 
In the terminal you can see the following issue:
```
Importing in unknown format: --importBibtex
Error opening file '--importBibtex': Could not find a suitable import format.
Importing: 
@book{elias_societe_1974
Error opening file '
@book{elias_societe_1974': Unknown import format: 
	address = {Paris
```

**Comment by yzgol** [comment]
Thanks for the anwser !
I don't know how to do it via the terminal, can you tell me ? jabref --importBibtex <url> ? 
And if you have the link to the discussion at hand, I'd like to have a look. I'm sorry I didn't found it.

**Comment by Siedlerchr** [comment]
Thanks to @LyzardKing  this should be fixed now in the edge? version of the snap soon
