### ISSUE TITLE
Extension preferences seem to have no effect

### ISSUE THREAD

**Issue by Socob** [JabRef/JabRef-Browser-Extension#172]
When going to the extension preferences (e. g. in Firefox), there are two settings “Export Format” and “Automatically take snapshots”. 

![Screenshot from 2020-05-12 16-16-26](https://user-images.githubusercontent.com/1915511/81702874-249eff00-946c-11ea-95d7-9a25ad5cbd7f.png)

However, neither of these actually seem to do anything. Perhaps they should be removed or their function explained in a bit more detail (e. g. “currently doesn’t do anything” if that is the case).

**Comment by tobiasdiez** [comment]
Thanks for your report. This should be fixed with https://github.com/JabRef/JabRef-Browser-Extension/pull/131. @systemoperator would you be willing to extract the relevant changes to a new PR (independent of the websocket & citation numbers) which could be merged quickly? Would be nice!

**Comment by systemoperator** [comment]
@tobiasdiez I could simply deactivate the websocket server and hide the setting for enabling fetching the citation counts, then everything else will look and work as usual and the aforementioned issues and other issues will be gone. Later on, we could enable the deactivated features as well. Would that be ok?

**Comment by tobiasdiez** [comment]
Yes, that would be good solution I think! We could also enable the citation fetcher, since this is already working (only without the update from JabRef's side), right? If you find the time, it would be nice if you could also finish the other PR at JabRef, so that we could let other users also enjoy the nice citation fetch feature.

**Comment by systemoperator** [comment]
Yes, the current PR is also usable without its counterpart with the websocket server in JabRef, allowing sending citation data with the corresponding citation count. In that case, we could prevent starting the websocket client, so that there are no connection errors.

**Comment by systemoperator** [comment]
Actually, the PR on JabRef's side is fully operational and tested steadily and thoroughly, but there are still some changes requested, where some of them seem quite time-consuming or where I am not fully sure how to adapt it. These two reasons and my current time constraint are my primary obstacles.

**Comment by tobiasdiez** [comment]
Ok, good. Could you then please https://github.com/JabRef/JabRef-Browser-Extension/pull/131 change accordingly and I'll merge it. Thanks!

I do understand that everybody is contributing in their freetime and that improving existing code is not as much fun as implementing a cool new feature from scratch. On the other hand, code architecture is very important to ensure maintainability in the future and we thus have high standards on this (perhaps too high...). Anyway, let's continue the discussion there and feel free to ask questions if some of the points are not clear yet. Thanks for your contributions! I'm a big fan of the citation fetcher!

**Comment by systemoperator** [comment]
Thanks, #131 can be merged. :)

**Comment by tobiasdiez** [comment]
Thanks to @systemoperator this is now fixed.
