### ISSUE TITLE
Parsing fails with xhr exception

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/JabRef-Browser-Extension#178]
> TypeError: can't access property "getAllResponseHeaders", xhr is undefined messages.js:223:5

for example on https://arxiv.org/abs/math/0101159

**Comment by LyzardKing** [comment]
It works for me with the latest snap edge (5.1.564) and the firefox extension...

**Comment by tobiasdiez** [comment]
Seems to be fixed indeed.
