### ISSUE TITLE
Can't export anything

### ISSUE THREAD

**Issue by ShawnGeller** [JabRef/JabRef-Browser-Extension#209]
Not sure what the problem is, but this extension isn't working for me. The error message I'm getting is

"Error while sending to JabRef, Please see the browsers error console for details."

In the browser error console it says:

TypeError: data is undefined at moz-extension://06687624-a731-416c-a2c9-cd5cca8ed0ae/Zotero/translate_item.js:134

I'm not sure how to troubleshoot this, maybe I've installed it incorrectly?

**Comment by LyzardKing** [comment]
Could you write here a url that fails on your system, so we can test it.
Also, what version of jabref are you running? And on which OS?

**Comment by ShawnGeller** [comment]
Sorry, I should have said. Here's an example url: https://arxiv.org/abs/2008.05488 but I get the same error independent of what website I'm on. Here's the info from about jabref:

JabRef 5.0--ArchLinux--3
Linux 5.7.14-1-manjaro amd64 
Java 14.0.2

**Comment by LyzardKing** [comment]
Does the file /opt/jabref/lib/jabrefHost.py exist?
It might have something to do with the arch package. Is it from AUR?

**Comment by ShawnGeller** [comment]
Apologies. I had installed incorrectly, into /opt/JabRef/, and also had forgotten to chmod the jabrefHost.py file. It's working now. Thank you!

**Comment by tobiasdiez** [comment]
Thanks for the feedback, glad it works now for you. @LyzardKing thanks for the assistance and you help!
