### ISSUE TITLE
JabRef on the New (2020) Microsoft Edge Browser

### ISSUE THREAD

**Issue by nicoborghi** [JabRef/JabRef-Browser-Extension#238]
Following the docs https://docs.jabref.org/collect/jabref-browser-extension for **Edge** I had the following Errors/Warnings:

Extension options tab:
`Connection Status: Access to the specified native messaging host is forbidden` 

Console error (When using the extension on ArXiv)
`TypeError: Cannot read property 'items' of null at [...] logError @ zotero.js:335` 

**Workaround solution**

1. CMD: `REG ADD "HKCU\Software\Microsoft\Edge\NativeMessagingHosts\org.jabref.jabref" /ve /t REG_SZ /d "C:\Program Files\JabRef\jabref-chrome.json" /f`. Note: \Microsoft\Edge\ (not described in the docs);

2. Open the Extension Options tab and copy the string after "?options=". It should be pgkajmkfgbehiomipedjhoddkejohfna. (different from the Chrome one);

3. This string should replace the one in the `jabref-chrome.json` file, that becomes:
```
{
  "name": "org.jabref.jabref",
  "description": "JabRef",
  "path": "JabRefHost.bat",
  "type": "stdio",
  "allowed_origins": [
    "chrome-extension://pgkajmkfgbehiomipedjhoddkejohfna/"
  ]
}
```

So, I would add a `jabref-edge.json` file with the correct extension ID and update the docs.

**Comment by LyzardKing** [comment]
A new json file is not needed, since it can have two origins.
@nicoborghi can you test if it this works?

```
{
  "name": "org.jabref.jabref",
  "description": "JabRef",
  "path": "JabRefHost.bat",
  "type": "stdio",
  "allowed_origins": [
    "chrome-extension://pgkajmkfgbehiomipedjhoddkejohfna/",
    "chrome-extension://bifehkofibaamoeaopjglfkddgkijdlh/"
  ]
}
```

**Comment by LyzardKing** [comment]
@tobiasdiez Is the regex line something we can add at install? Like we do on the other systems..

**Comment by nicoborghi** [comment]
> A new json file is not needed, since it can have two origins.
> @nicoborghi can you test if it this works?
> 
> ```
> {
>   "name": "org.jabref.jabref",
>   "description": "JabRef",
>   "path": "JabRefHost.bat",
>   "type": "stdio",
>   "allowed_origins": [
>     "chrome-extension://pgkajmkfgbehiomipedjhoddkejohfna/",
>     "chrome-extension://bifehkofibaamoeaopjglfkddgkijdlh/"
>   ]
> }
> ```

Yes, it works!
