### ISSUE TITLE
Adblock extension interferes with the functioning of the extensions

### ISSUE THREAD

**Issue by eugenio** [JabRef/JabRef-Browser-Extension#241]
I have no idea how or why, please guide me into diagnose the problem more in detail but I noticed that if I have a page on which adblock plus is working on, jabref extension doesn't work at all.
For now i noticed the problem on Ubuntu and Google-chrome but I suspect that the issue is related to the adblock plus extension and thus more generally spread on those system that use it no matter on the os and browser.
I will try to confirm this soon on my systems.
Anyway great work, I really appreciate Jabref and the extension!
Thank you!

**Comment by LyzardKing** [comment]
can you open the inspector and see what it logs in the console when you run the extension?
Both with and without adblock...

**Comment by eugenio** [comment]
> can you open the inspector and see what it logs in the console when you run the extension?
> Both with and without adblock...

Here you have attached two log files with and without adblock:

[www.sciencedirect.com-1604837997661-without-adblock.log](https://github.com/JabRef/JabRef-Browser-Extension/files/5506307/www.sciencedirect.com-1604837997661-without-adblock.log)

[www.sciencedirect.com-1604837997661-with-adblock.log](https://github.com/JabRef/JabRef-Browser-Extension/files/5506308/www.sciencedirect.com-1604837997661-with-adblock.log)

please let me know if you are in need of more info.

**Comment by LyzardKing** [comment]
Can you post the url you're trying to parse?

**Comment by eugenio** [comment]
Sorry I thought it was included in the logs. 
Anyway it should be this one:
[https://www.sciencedirect.com/science/article/pii/S0960852419309368](https://www.sciencedirect.com/science/article/pii/S0960852419309368)

**Comment by tobiasdiez** [comment]
When you click on the button, the extension downloads the "translator" code (the code responsible of extracting the bibliographic information). The logs suggest that adblock is blocking this download and hence the extension is not able to extract anything meaningful from the website.

I'm not using adblock, but you probably have a way to see which websites/downloads it blocked. There you should allow download from zotero's servers. You should be able to see which urls are blocked from the "More tools > Developer tools > Network" view.

**Comment by eugenio** [comment]
I can confirm that with the suggestion of @tobiasdiez the issue seem to be solved.
What I did is to go to zotero.org website and authorize the full domain in adblock-plus.
I'm not sure is the best solution but seem to be working for me!
Many thanks for the help!

**Comment by tobiasdiez** [comment]
Good to hear!

Could you please add a "Troubleshooting" section at the bottom of https://github.com/JabRef/user-documentation/edit/master/en/collect/jabref-browser-extension.md with a short description of what you did to fix this problem. Then other users have an easier life. Thanks!

**Comment by LyzardKing** [comment]
@tobiasdiez It's strange, because I cannot replicate the issue.
I checked the default lists used by adblock plus, and there is no mention of zotero

**Comment by tobiasdiez** [comment]
I guess it's probably in one of the more aggressive lists...
