### ISSUE TITLE
Option page scrollbar vibration

### ISSUE THREAD

**Issue by clecap** [JabRef/JabRef-Browser-Extension#272]
Opening the option page of the extension produces a "scrollbar vibration". See screen movie attached.

Effect is reproducible and shows up on extension version 2.4 installed on Chrome 88.0.4324.96 (Official Build) (x86_64) on MacOs 10.15.6.

https://user-images.githubusercontent.com/7084049/106399517-61a38b00-6419-11eb-9805-9ff0708cdbb0.mov

**Comment by tobiasdiez** [comment]
I can now longer reproduce this; thus closing for now. Let me know if it still persists for you and I'll reopen it (although I have no idea where this issue would come from).
