### ISSUE TITLE
Failed to load SourceMap in Chromium based browser - sends empty entry to Jabref

### ISSUE THREAD

**Issue by cballam** [JabRef/JabRef-Browser-Extension#301]
I've been using this extension for a while now and have only started to have some issues with it this week. I'm using this extension (version 2.4) mainly in Google Chrome (version 89.0.4389.114 if relevant), on Windows 10. I have also tried the Brave browser, and get similar errors. Specifically:
![image](https://user-images.githubusercontent.com/27101846/114110117-1d050600-991a-11eb-9b2a-9b14cb1ac8b7.png)
It seems that there's the one file which fails to load, and then for some reason is unable to get any data from each page and sends an empty object to jabref. This is on IEEEXplore, which I have found very reliable in the past. Other websites like Scopus give the same result. 
Checking the devtools console seems to reach the same result (this is from clicking the plugin once on that IEEXplore page)
![image](https://user-images.githubusercontent.com/27101846/114110543-1aef7700-991b-11eb-8390-efa96c02ea8a.png)
I have tried a hard reload, reinstalling plugin etc. All seem to lead to this same issue. I haven't found this browser-polyfill-min.js file in the extension anywhere, so I'm not quire sure what would be using it. 
Any suggestions on how to fix are much appreciated as I couldn't find any relevant issues.

**Comment by cballam** [comment]
After toying around with this for the last 30mins I believe I may have solved the problem. [Docs here](https://docs.jabref.org/collect/jabref-browser-extension) said that Zotero adblocking needed to be deactivated, so I did this in Brave. Apparently this was most of what I needed to do to fix the problem for that browser - I still get the "failed to load SourceMap" warning in the console, but it doesn't prevent the extension from doing its job. Chrome was a little bit weirder though. The problem with it not working may have been related to the extension in Brave working. When I closed the Brave browser entirely and hard refreshed Chrome, the extension would work as normal. As soon as I open Brave, things stop working in Chrome and work fine in Brave. 

Both say that the communication to JabRef is successful in the extensions tab, so I'm not quite sure what could be causing it. Either way, easiest fix is to just use one browser (perhaps one Chromium based browser, haven't tried Firefox) with the extension at a time.

**Comment by tobiasdiez** [comment]
I'm glad you could find a solution! I had a second look, but couldn't find a way to give a more useful error message (for example to see why the add blocker needs  to be disabled). Chrome just doesn't return any error details for the `sendMessage` command that is used for the communication with JabRef.

By the way, the initial warning about the source map can safely be ignored. Source maps are only needed for debugging, to map code points in a minified version back to the original code file.
