### ISSUE TITLE
Error while sending to JabRef.

### ISSUE THREAD

**Issue by starsareintherose** [JabRef/JabRef-Browser-Extension#345]
Error while sending to JabRef.
Please see the browsers error console for details.
[zookeys.pensoft.net-1629103815705.log](https://github.com/JabRef/JabRef-Browser-Extension/files/6990964/zookeys.pensoft.net-1629103815705.log)
OS: ArchLinux
Extension: Chrome

**Comment by tobiasdiez** [comment]
Does this occur on every website?

**Comment by starsareintherose** [comment]
Right

**Comment by starsareintherose** [comment]
That's working, sorry for this report, I haven't configured`~/.config/microsoft-edge-dev/NativeMessagingHosts/org.jabref.jabref.json`

**Comment by starsareintherose** [comment]
That's working, sorry for this report, I haven't configured`~/.config/microsoft-edge-dev/NativeMessagingHosts/org.jabref.jabref.json`
