### ISSUE TITLE
Error while sending to JabRef (Linux)

### ISSUE THREAD

**Issue by cyprienruffino** [JabRef/JabRef-Browser-Extension#381]
Piggybacking on  issue #278 
This time, on ArchLinux (5.15.4), with Mozilla Firefox 94.0.2.

I get the error :
"Error while sending to JabRef.
Please see the browsers error console for details."

In the console,
No such native application org.jabref.jabref

I tried installing JabRef manually from the git and from the AUR repos.

Same as  issue #278 , in the add-on setting, it says : "Connection status : Attempt to postMessage on disconnected port" and "Websocket status : Websocket client not started"

Thank you !

**Comment by LyzardKing** [comment]
If you install from the git repo or AUR you have to install the native messaging part manually (as described at https://docs.jabref.org/collect/jabref-browser-extension).

**Comment by cyprienruffino** [comment]
Wow, now that was a quick answer. Shame on me for not reading the doc thoroughly.
Thanks, closing issue.
