### ISSUE TITLE
Stalled at "Searching for bibliographic data..." with error "TypeError: this._translatorInfo is undefined" from translate.js:2391:22 in Firefox 

### ISSUE THREAD

**Issue by wavemaking** [JabRef/JabRef-Browser-Extension#389]
Since recently I can't use the browser extension anymore to fetch bibliographic data. It stalls at "Searching for bibliographic data..."

This occurs both in Firefox and in Chrome on Windows 10. I tried both Jabref 5.3 and 5.2 (both portable, following the additional instructions on .bat and .ps1 files). It happens both on scholar.google.com  and arxiv.org. In fact, I can't find a site that works. But I tested these two several times.

In the Firefox console I get:
TypeError: this._translatorInfo is undefined5 translate.js:2391:22

In the Chrome console I get:
translate.js:2391 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'configOptions')
    at Zotero.Translate.Import.<anonymous> (translate.js:2391)
    at Zotero.Translate.Import._loadTranslatorPrepareIO (promise.js:34)
    at Zotero.Translate.Import.<anonymous> (translate.js:2383)

I'm by far no expert in javascript, but I'm happy to follow instructions to debug this error (or to stand corrected on a configuration error on my part....).

**Comment by wavemaking** [comment]
This issue resolved itself when I upgraded to Jabref 5.4 and after having updated the windows registry as per the instructions at https://docs.jabref.org/collect/jabref-browser-extension#windows

Closing this.

**Comment by tobiasdiez** [comment]
That's good to hear! I'm happy its now working for you.
Sorry for not having reacted to your initial message; been a bit busy here lately.
