### ISSUE TITLE
Trouble with Edge plugin

### ISSUE THREAD

**Issue by MacGyver00** [JabRef/JabRef-Browser-Extension#444]
I have trouble with Edge plugin. I am using latest Jabref 5.6 beta portable on win10 with all recent updates.
I have installed Edge plugin and followed the manual installation instructions described [here](https://docs.jabref.org/collect/jabref-browser-extension#installation-and-configuration)

When try to use the plugin I receive the following error:
![image](https://user-images.githubusercontent.com/60260220/163578832-cab6ef15-4523-4b53-804a-30009db523fe.png)

On pressing Ctrl-Shift-J on Edge, the following warning is shown:
" [cdn.tailwindcss.com](http://cdn.tailwindcss.com/) should not be used in production. To use Tailwind CSS in production, install it as a PostCSS plugin or use the Tailwind CLI: [Installation: Tailwind CLI - Tailwind CSS](https://tailwindcss.com/docs/installation)
(anonymous) @ (index):62"

Note 1: Powershell 7 is installed. Firefox plugin works without problem. 
Note 2: Issue was first reported [here](https://discourse.jabref.org/t/trouble-with-edge-plugin/3327)
Any ideas?

**Comment by tobiasdiez** [comment]
Do you use the new Chromium based Edge or the old "legacy" edge that comes as default with win 10?
https://support.microsoft.com/en-us/microsoft-edge/what-is-microsoft-edge-legacy-3e779e55-4c55-08e6-ecc8-2333768c0fb0

**Comment by MacGyver00** [comment]
The Chromium based Edge Version 100.0.1185.44 (Official build) (64-bit)

**Comment by MacGyver00** [comment]
For an unknown reason (most likely due to the last Edge update) problem is magically solved! Edge plugin can now  connect and send  the corresponding entries to Jabref. So I think that the issue can be considered as solved. Thanks for your help.
