### ISSUE TITLE
Failed to fetch data from Contile server

### ISSUE THREAD

**Issue by lidans5** [JabRef/JabRef-Browser-Extension#462]
I'm getting the following message when using jabref add-on with firefox and trying to add an entry from some university sites:
TopSitesFeed: Failed to fetch data from Contile server: NetworkError when attempting to fetch resource.

**Comment by tobiasdiez** [comment]
Can you please provide more details so that I can try to reproduce it: when do you get this error, on which websites, etc?

**Comment by lidans5** [comment]
I don't know, I reinstalled it, and everything works fine now...

**Comment by tobiasdiez** [comment]
Okay, good to hear! In this case, I'll close this issue now. Feel free to reopen it if the issue should return.
