### ISSUE TITLE
JabRef-Browser-Extension does not work on Chrome

### ISSUE THREAD

**Issue by SpaceWalker162** [JabRef/JabRef-Browser-Extension#464]
It was one or two years ago the last time the extension worked on my Chrome. When I click the extension's icon, it pops up a menu, and does nothing more, like shown in the screenshot
![image](https://user-images.githubusercontent.com/56574868/172036361-8bdbcd9d-1de8-47ed-b5ac-a1f2a2479fe0.png)

**Comment by tobiasdiez** [comment]
You need to click on the first menu item "JabRef Browser Extension". It's sadly a visual limitation of the Chrome extension framework.

**Comment by SpaceWalker162** [comment]
Thank you for your comment. I switched to MacOS machine. The extension works on Chrome on the new machine. On the old machine, I did try to cIick every available button but got null result.
