### ISSUE TITLE
Browser extension import not working

### ISSUE THREAD

**Issue by Tobi0** [JabRef/JabRef-Browser-Extension#479]
### JabRef version

5.6 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10 20H2 19042.1706

### Checked with the latest development build

- [ ] I made a backup of my libraries before testing the latest development version.
- [ ] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

This seems to occur on Windows only if `pwsh.exe` is not installed, but `powershell.exe` installed.

### Issue
The Jabref Browser Extension (Firefox) shows "Error while sending to JabRef" and no reaction from the client at all (either opened or not). 

### Possible Cause
This change on `buildres/windows/JabRefHost.bat`: https://github.com/JabRef/jabref/pull/8432
There is probably an issue with the errorlevel check.
If I change the file back to only the `@powershell.exe` command, it works.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by ThiloteE** [comment]
The transfer from JabRef/JabRef to JabRef/JabRef-Browser-Extension created new labels "type bug" and "os:windows", which i can't get rid off. Sorry :/

**Comment by tobiasdiez** [comment]
Thanks for the investigation @Tobi0! I think you are right, the second `%errorlevel%` does not reflect the outcome of the second test. In fact, a similar question has been raised here https://stackoverflow.com/questions/50348437/wrong-value-of-errorlevel-in-nested-if-in-bat-file. Could you please try the workaround/fix posted there, and if it indeed works open a PR at the jabref repo? That would be awesome!
