### ISSUE TITLE
JabRef in Firefox not working

### ISSUE THREAD

**Issue by Oliver-Chalkley** [JabRef/JabRef-Browser-Extension#480]
Windows 10: After installing JabRef and the Firefox add-on, when I try to add a reference by clicking on the JabRef icon in firefox I get taken the this page. 

[moz-extension://52d1868a-7663-4f74-a1b5-db221a5115ce/data/error.html?message=An%20unexpected%20error%20occurred&details=&stacktrace=](url)

![image](https://user-images.githubusercontent.com/37191771/178937647-2be9f133-dbcc-4a16-8ba4-0f273f0afc71.png)

**Comment by songcailing** [comment]
I get the same error. The error is reported in the browser console and extension options as shown in the figure. At the same time, clicking on the extension icon in the article link https://pubmed.ncbi.nlm.nih.gov/29247356/ only stops at the first step "Searching for bibliographic data...", but in other pages such as https://docs.jabref.org/collect/jabref-browser-extension#installation-and-configuration Clicking the extension icon works and an error page appears
![微信图片_20220714213925](https://user-images.githubusercontent.com/109291439/178995915-3273b57b-645d-482d-802d-d05fd7e0119f.png)
![微信图片_20220714213933](https://user-images.githubusercontent.com/109291439/178995945-35f443c6-d26f-49b0-a380-159723d15c96.png)
![微信图片_20220714213937](https://user-images.githubusercontent.com/109291439/178995956-cec12a5f-124e-47c3-bcdf-4fb0679a77d0.png)
![微信图片_20220714214054](https://user-images.githubusercontent.com/109291439/178996154-2e8ecd6b-5b55-40d6-957c-7f425695cdd6.png)
.

**Comment by songcailing** [comment]
I solved this problem by upgrading powershell to version 7.0 @Xavier-B1

**Comment by Xavier-B1** [comment]
Excellent, having updated Powershell to version 7.2, importing citations in JabRef now works!
Thank you!

**Comment by Siedlerchr** [comment]
The newest JabRef Version 5.7 contains a fix for the detection of PowerShell and pwsh
