### ISSUE TITLE
Add option to not import abstract?

### ISSUE THREAD

**Issue by nujabse** [JabRef/JabRef-Browser-Extension#485]
Using the latest chrome extension (version 2.5), Jabref always writes the **abstract** of the article in the exported bibtex file. However, some articles have very long lines in the abstract field which I wish can skip in the import process.

**Comment by tobiasdiez** [comment]
I understand your concern but adding functionality that allow users to post-process the bibtex will opening a big project with no clear boundaries (the next user would like to have normalized dates, the next one doesn't care about the url etc). 

So I think it best to handle this on JabRef's side. In fact, there we have the cleanup operations which allow you to run a "field formatter" that cleans the content. This should be suitable for your use case. See https://docs.jabref.org/finding-sorting-and-cleaning-entries/cleanupentries. I guess the export-import-cleanup process could be made even more convenient, and if you have ideas of how to do this please feel free to open a new issue (then probably at the main jabref repo).
