### ISSUE TITLE
Should inform about missing JabRef or wrong version of existing JabRef

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [JabRef/JabRef-Browser-Extension#51]
Suprisingly JabFox 2.1.1 showed up in the adressbar of my Firefox 59.0.2 on Debian unstable. Nice.

There are no errows while clicking on it. But the data never arrive at JabRef - because only JabRef 3.8 is installed on my system. I know that the new JabFox only works with JabRef 4.x.

If there is a way... JabFox should check if the export was successfull and inform the user if not.

**Comment by tobiasdiez** [comment]
This is now implemented in the latest development version (which will be published with the release of JabRef 5.0). Sadly, firefox does not directly provide the error details but only logs it. Thus I had to refer the user to the browser console.
