### ISSUE TITLE
File at path "/opt/jabref/lib/jabrefHost.py" does not exist, or is not executable

### ISSUE THREAD

**Issue by dbitouze** [JabRef/JabRef-Browser-Extension#541]
When `JabRef` is installed on GNU/Linux:

- thanks to [JabRef Linux portable](https://www.fosshub.com/JabRef.html),
-  in a customized repository,

`JabRef Browser Extension` doesn't work because:

> File at path "/opt/jabref/lib/jabrefHost.py" does not exist, or is not executable

I didn't find any way to customize the path of `jabrefHost.py` in `JabRef Browser Extension`: is it possible?

**Comment by tobiasdiez** [comment]
There is a `org.jabref.jabref.json` file somewhere (see https://docs.jabref.org/collect/jabref-browser-extension#linux) (if not you should create one), which allows you to configure the path to the python file.

Feel free to reopen if this doesn't help.
