### ISSUE TITLE
Jabfox only recognizes bibliographic information if the tab and window are active

### ISSUE THREAD

**Issue by davidcbenson** [JabRef/JabRef-Browser-Extension#55]
TBH, I am unsure if this is an issue or a configuration problem, but I have tried as much troubleshooting as I can, and have been unable to tell, so I am reporting it here.

When opening any reference I expect to cite, in most cases the Jabfox Icon works just fine. If I navigate away for any reason (open another tab, open the citation in a separate tab, pause my music) when I come back I will be unable to download the citation. It can sometimes take a while to load the JabFox icon, which I assume is because the internet here can be slow sometimes and it is looking up the data somewhere. This delay makes what otherwise would not be a big issue into an inconvenience I would prefer to avoid.

JabRef 4.3.1
Windows 10 10.0 amd64 
Java 1.8.0_181
JabFox 2.1.1

**Comment by tobiasdiez** [comment]
This should be fixed in the new version that will be released simultaneously to JabRef 5.0.
