### ISSUE TITLE
Edge extension cannot connect to JabRef

### ISSUE THREAD

**Issue by drcxd** [JabRef/JabRef-Browser-Extension#552]
Hi,

I know this is a recurring issue. I have seen similar problem here https://github.com/JabRef/JabRef-Browser-Extension/issues/444. However, I do not find solution there.

My portable JabRef version is:

JabRef 5.9--2023-01-08--76253f1a7
Windows 10 10.0 amd64 
Java 19.0.1 
JavaFX 19+11

Edge version is Version 111.0.1661.43 (Official build) (64-bit), which I believe is based on chromium.

The error message is:

```
Error: Specified native messaging host not found. at chrome-extension://pgkajmkfgbehiomipedjhoddkejohfna/browser-polyfill.min.js:1:6365
```

The console says:
```
(index):64 
        
       cdn.tailwindcss.com should not be used in production. To use Tailwind CSS in production, install it as a PostCSS plugin or use the Tailwind CLI: https://tailwindcss.com/docs/installation
(anonymous) @ (index):64
```

I have installed the extension through Edge. I checked the manual installation manual. It suggested executing the following code:
```
REG ADD "HKEY_LOCAL_MACHINE\Software\Microsoft\Edge\NativeMessagingHosts\org.jabref.jabref" /ve /t REG_SZ /d "C:\path\to\jabref.json" /f
```

However, I could not find the file `jabref.json`. I could find `jabref-chrome.json` and `jabref-firefox.json` in the program's root directory.

**Comment by tobiasdiez** [comment]
Good point, the manual installation instructions are too vague here. Edge uses the same engine as chrome, so it should work if you use `jabref-chrome.json` and rename to `jabref.json`.

**Comment by drcxd** [comment]
I have tried using `jabref-chrome.json`, but that does not help with the problem. Also, I suppose install the plugin in Edge should also work?

**Comment by bhatiaa1** [comment]
I tried out the portable version of development build on Windows 10, and I followed the instructions for making the Edge extension talk to the existing instance of Jabref and I see the exact same problem.

Jabref did not start on my install of Windows 10, I had to use "troubleshoot compatibility" option in Windows and it recommended and applied the Windows 8 settings for Jabref. After this Jabref does start up, but the browser extension fails to connect to the running instance.

JabRef 5.10--2023-07-12--fd82bef
Windows 10 10.0 amd64 
Java 21-internal 
JavaFX 20+19

In the browser console, I see the following same message as above -
"(index):62  cdn.tailwindcss.com should not be used in production. To use Tailwind CSS in production, install it as a PostCSS plugin or use the Tailwind CLI: https://tailwindcss.com/docs/installation"

**Comment by paddomanno** [comment]
i have a similar problem using the edge extension, not sure if this is the same or if I should make a separate issue.

Any time I click the edge extension to send a page to JabRef, it works (the popup opens in the JabRef win10 desktop app) and I can import the data just fine, but a brwoser window opens saying:

```
Error connecting to JabRef
Error when communicating with the native messaging host.
Unknown error while sending to JabRef.
Error: Error when communicating with the native messaging host. at chrome-extension://pgkajmkfgbehiomipedjhoddkejohfna/browser-polyfill.min.js:1:6365
```

There are no errors in the console (only the warning about tailwind).
Nothing in the desktop app's logs.

It seems like everything is working fine and there is no reason for the error message.

"Listen for remote operation on port" is turned on, I specified port 6365 since that was what the error said but it didn't change anytihng.

JabRef 5.10--2023-09-01--779e555
Windows 11 10.0 amd64 
Java 21-internal 
JavaFX 20+19

JabRef Browser Extension for Edge v2.5 says
Connection Status: Communication to JabRef successful!
Websocket Status: Websocket client not started

MS Edge Version 118.0.2088.46

**Comment by kanosora** [comment]
> i have a similar problem using the edge extension, not sure if this is the same or if I should make a separate issue.
> 
> Any time I click the edge extension to send a page to JabRef, it works (the popup opens in the JabRef win10 desktop app) and I can import the data just fine, but a brwoser window opens saying:
> 
> ```
> Error connecting to JabRef
> Error when communicating with the native messaging host.
> Unknown error while sending to JabRef.
> Error: Error when communicating with the native messaging host. at chrome-extension://pgkajmkfgbehiomipedjhoddkejohfna/browser-polyfill.min.js:1:6365
> ```
> 
> There are no errors in the console (only the warning about tailwind). Nothing in the desktop app's logs.
> 
> It seems like everything is working fine and there is no reason for the error message.
> 
> "Listen for remote operation on port" is turned on, I specified port 6365 since that was what the error said but it didn't change anytihng.
> 
> JabRef 5.10--2023-09-01--779e555 Windows 11 10.0 amd64 Java 21-internal JavaFX 20+19
> 
> JabRef Browser Extension for Edge v2.5 says Connection Status: Communication to JabRef successful! Websocket Status: Websocket client not started
> 
> MS Edge Version 118.0.2088.46

same problem with WINDOWS 11 22631.3155

**Comment by drcxd** [comment]
I found that the manual installation (https://docs.jabref.org/collect/jabref-browser-extension#manual-installation) solves the problem now. The extension version is 2.5, JabRef verison is 5.12, and Edge version is 122.0.2365.92.

**Comment by tobiasdiez** [comment]
@drcxd That's awesome news! What did you had to change/add during the manual installation? Normally, everything should be setup automatically during the installation of the main JabRef program.

**Comment by drcxd** [comment]
@tobiasdiez I just did what the doucmentation said. Actually I do not remember why it did not work last year.  One thing worth noting is that I am using the portable version, so a manual installation is necessary, but I guess I did not realize that last year. (Maybe I did not read the document carefully, that was my bad.) According to the initial comment, the `jabref.json` file was missing in that particular release. Now the file is there and after the manual installation the extension can correctly sends the bibliographic data to JabRef, so I guess everything is fine now.

**Comment by drcxd** [comment]
Hello, @tobiasdiez,

I have updated to 5.13 today and found that the released portable verision does not contain the file `jabref.json`. Can you add it to  the release? Or maybe you can update the document of manual installation so that users of Edge may know they have to rename `jabref-corme.json` to `jabref.json`.

> Good point, the manual installation instructions are too vague here. Edge uses the same engine as chrome, so it should work if you use `jabref-chrome.json` and rename to `jabref.json`.
