### ISSUE TITLE
Error connecting to JabRef after update to MacOS Ventura 13.3.1

### ISSUE THREAD

**Issue by cowniflow** [JabRef/JabRef-Browser-Extension#562]
When trying to use the JabRef Browser Extension for Firefox, I get the following message:

"An unexpected error occurred
Unknown error while sending to JabRef.
Please see the browsers error console for details (press Ctrl-Shift-J) and follow the [manual installation instructions](https://docs.jabref.org/collect/jabref-browser-extension#installation-and-configuration) to make sure your setup is correct."

The browser error console looks like this: 
![Screenshot 2023-04-20 at 14 27 34](https://user-images.githubusercontent.com/83248692/233365977-65f3e878-cc1b-4a96-a5cd-df4992dbaf43.png)

I've been having the problem since the update to MacOS Ventura 13.3.1. 

I already tried reinstalling both JabRef and the Browser Extension and checked that jabrefHost.py and org.jabref.jabref.json are in the right place.

Further Info: 
JabRef 5.9--2023-01-08--76253f1a7
Mac OS X 13.3.1 x86_64 
Java 19.0.1 
JavaFX 19+11

**Comment by tobiasdiez** [comment]
I'm sorry that you experience these issues, but sadly with the information provided it's hard to help. The error console doesn't contain more information on whats wrong (sadly browsers often don't give detailed error messages...). So my only advice would be to go through the manual installation steps, but this you already did. 

A shot in the dark: try to reinstall firefox as well. There are a few strange error messages in the console (eg. profile directory not found). Maybe this helps...

**Comment by cowniflow** [comment]
Thanks for the quick reply. Unfortunately, reinstalling Firefox did not help. I'll give an update if I find out more.

**Comment by cowniflow** [comment]
Sorry, correction: It did work! I also had to delete all Firefox service files from the cache. I had not done that when I reinstalled at first. Now everything is back to normal with the JabRef extension. Thanks.

**Comment by tobiasdiez** [comment]
Happy it works for you again!
