### ISSUE TITLE
JabRef Extension on LibreWolf

### ISSUE THREAD

**Issue by oceanmattes** [JabRef/JabRef-Browser-Extension#565]
Hello,

I installed JabRef and the Firefox Web Extension (LibereWolf is a custom and independent version of Firefox) placed the .json File in the right folder an checked the path and deactivated my ad blocker. When I'm using Firefox the extension works just fine, but i cant get it running with LibreWolf. Any ideas, or is it just impossible to use the extension with LibreWolf?

Thanks

**Comment by tobiasdiez** [comment]
I have no experience with LibreWolf, but did you tried https://librewolf.net/docs/faq/#how-do-i-get-native-messaging-to-work? What error message is shown in the browser console?

**Comment by oceanmattes** [comment]
Thanks for the quick answer, this was the part that i missed ;)
