### ISSUE TITLE
Jabfox doesn't work

### ISSUE THREAD

**Issue by henrymartin1** [JabRef/JabRef-Browser-Extension#57]
Hi, 
I have the issue, that the Jabfox button is not appearing and that I can't connect it to my Jabref. Is this an issue with the Firefox version? If so, which one is currently supported?

System Information:
Windows 10 (64bit) 
Firefox 64.0.2
Jabref 4.3.1

Here is the relevant registry entry:

![image](https://user-images.githubusercontent.com/31069329/51601968-125f2180-1f06-11e9-8254-d75d819d4450.png)

And the content of my jabref.json file:
{
  "name": "org.jabref.jabref",
  "description": "JabRef",
  "path": "JabRef.bat",
  "type": "stdio",
  "allowed_extensions": [
    "@jabfox"
  ]
}

Here is a screenshot form the jabfox options window:
![image](https://user-images.githubusercontent.com/31069329/51602092-6833c980-1f06-11e9-9a8c-baca243020ee.png)

Here are some Jabref preferences:
![image](https://user-images.githubusercontent.com/31069329/51602338-f9a33b80-1f06-11e9-85e2-de8b5493de46.png)

Thanks for your help!

**Comment by AEgit** [comment]
JabRef 5.0.0-dev--2019-10-21----0f0dce621
Windows 10 10.0 amd64 
Java 12.0.2

JabFox 2.1.2
Firefox 70.0

Cannot confirm. JabFox works as expected for me.

**Comment by tobiasdiez** [comment]
This should be fixed with the new version that will be released simultaneously with JabRef 5.0.
