### ISSUE TITLE
Error connecting to JabRef

### ISSUE THREAD

**Issue by lewinglch** [JabRef/JabRef-Browser-Extension#576]
Unknown error while sending to JabRef. Using JabRef Extension on Mac's Mozilla Firefox. 

Here's my browser error console: 

1685024645210	addons.xpi	WARN	Checking /Applications/Firefox.app/Contents/Resources/distribution/extensions for addons
1685024645561	addons.webextension.@jabfox	WARN	Loading extension '@jabfox': Reading manifest: Warning processing key: An unexpected property was found in the WebExtension manifest.
SessionStore: The session file is invalid: TypeError: state.windows[0] is undefined [SessionStore.sys.mjs:933:19](resource:///modules/sessionstore/SessionStore.sys.mjs)
    initSession resource:///modules/sessionstore/SessionStore.sys.mjs:933
    onBeforeBrowserWindowShown resource:///modules/sessionstore/SessionStore.sys.mjs:1863
BackgroundUpdate: _reasonsToNotScheduleUpdates: Failed to check for Maintenance Service Registry Key: [Exception... "Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [nsIUpdateProcessor.getServiceRegKeyExists]"  nsresult: "0x80004001 (NS_ERROR_NOT_IMPLEMENTED)"  location: "JS frame :: resource://gre/modules/BackgroundUpdate.sys.mjs :: _reasonsToNotScheduleUpdates :: line 247"  data: no] [BackgroundUpdate.sys.mjs:249](resource://gre/modules/BackgroundUpdate.sys.mjs)
stderr output from native app org.jabref.jabref: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
DOMException: Could not parse path (null): NS_ERROR_FILE_UNRECOGNIZED_PATH
    _getChromeUserDataPathIfExists resource:///modules/ChromeProfileMigrator.sys.mjs:109
[MigratorBase.sys.mjs:562:15](resource:///modules/MigratorBase.sys.mjs)
    isSourceAvailable resource:///modules/MigratorBase.sys.mjs:562
DOMException: Could not parse path (null): NS_ERROR_FILE_UNRECOGNIZED_PATH
    _getChromeUserDataPathIfExists resource:///modules/ChromeProfileMigrator.sys.mjs:109
[MigratorBase.sys.mjs:562:15](resource:///modules/MigratorBase.sys.mjs)
    isSourceAvailable resource:///modules/MigratorBase.sys.mjs:562

Can anyone help me to fix my problem? 

Thank you!

**Comment by tobiasdiez** [comment]
Not sure where this comes from but "xcrun: error: invalid active developer path" should be fixed by installing xcode as described in https://apple.stackexchange.com/questions/254380/why-am-i-getting-an-invalid-active-developer-path-when-attempting-to-use-git-a.

**Comment by lewinglch** [comment]
It worked! Thank you so much!

**Comment by tobiasdiez** [comment]
Happy to hear!
