### ISSUE TITLE
ReferenceError on particular site

### ISSUE THREAD

**Issue by rolandog** [JabRef/JabRef-Browser-Extension#58]
Hi.

I'm getting a ReferenceError in the log when I visit `https://decide.sanpedro.gob.mx/`:

<details><summary>Error message:</summary>

```
ReferenceError: TLDS is not defined at moz-extension://0b587c9f-8c9c-4b04-94ee-cc23ae87564b/Zotero/messaging_inject.js:76 zotero.js:284:4
    logError moz-extension://0b587c9f-8c9c-4b04-94ee-cc23ae87564b/Zotero/zotero.js:284
    getTranslators moz-extension://0b587c9f-8c9c-4b04-94ee-cc23ae87564b/Zotero/translate.js:1248
```
</details>

<details><summary>JabRef version:</summary>

```
JabRef 4.3.1
Windows 10 10.0 amd64 
Java 1.8.0_181
```
</details>

<details><summary>JabFox version:</summary>

```
version 2.1.1
```
</details>

<details><summary>FireFox version:</summary>

```
66.0 (64-bit)
```
</details>

<details><summary>Windows version:</summary>

```
OS Name	Microsoft Windows 10 Pro
Version	10.0.17763 Build 17763
```
</details>

Any clues to what could be wrong?

**Comment by tobiasdiez** [comment]
This site seems to be unavailable, so I cannot test but the "TLDS" error should be fixed in the next release.
