### ISSUE TITLE
Create entry from found dois in text

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/JabRef-Browser-Extension#60]
Today I was on a library PC with Citaviy Picker installed and noticed that after a disvovered DOI it added a symbol to automatically pick the doi to create a reference.

Something like this would be cool as well

![grafik](https://user-images.githubusercontent.com/320228/55633639-1ee0df80-57bd-11e9-8226-e47c84d72deb.png)

**Comment by tobiasdiez** [comment]
Out of scope for now, but PRs are warmly welcome!
