### ISSUE TITLE
URL not imported (from researchgate)

### ISSUE THREAD

**Issue by the-dino-girl** [JabRef/JabRef-Browser-Extension#600]
### JabRef version

5.9 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10 22H2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Go to https://www.researchgate.net/publication/362680358_A_new_chasmosaurine_ceratopsid_from_the_Upper_Cretaceous_Campanian_Farmington_Member_of_the_Kirtland_Formation_New_Mexico
2. Run firefox extension
3. Add this paper
4. See that the "URL" field in jabref is not filled in with this URL

Another example is the following URL which is not imported:

https://www.researchgate.net/publication/256093697_Histological_core_drilling_A_less_destructive_method_for_studying_bone_histology

But the same paper on a different URL has a URL field imported:

https://www.academia.edu/625268/HISTOLOGICAL_CORE_DRILLING_A_LESS_DESTRUCTIVE_METHOD_FOR_STUDYING_BONE_HISTOLOGY

Is this a bug only for researchgate? I don't know...

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by tobiasdiez** [comment]
I believe this is a bug / mishandling in the Zotero translator used for researchgate. There they add the "url" as an attachment (https://github.com/zotero/translators/blob/5187948c67b07cacdcc2ab89145a903bdb80263e/ResearchGate.js#L152C4-L156), while for the embedded metadata translator used for academia.edu the `url` field is set (https://github.com/zotero/translators/blob/5187948c67b07cacdcc2ab89145a903bdb80263e/Embedded%20Metadata.js#L576-L579).
I've opened https://github.com/zotero/translators/issues/3123 to track this.

**Comment by the-dino-girl** [comment]
So Zotero is used for the jabref extension?

**Comment by tobiasdiez** [comment]
Yes, the zotero translators (not the main zotero program) are used.

**Comment by the-dino-girl** [comment]
> Yes, the zotero translators (not the main zotero program) are used.

I'would be interested in docs about the browser extension if you ever have time.
Just some overview how it works and how the communication between extension and jabref works (for non-developers).

**Comment by the-dino-girl** [comment]
In order to report bugs and to know what websites are really supported by the extension, can you maybe answer my question here?

https://discourse.jabref.org/t/browser-extension-supported-journals/3969

**Comment by the-dino-girl** [comment]
There is an answer on github of zotero but I have no idea what they mean. According to me your issue is right!
They just need to use the url field.

**Comment by tobiasdiez** [comment]
The point is that the researchgate url is not the "right" url for the paper (which would be the url of the paper at the journal). Instead zotero simply adds the url as an attachment (here is another example for semantic scholar: https://github.com/zotero/translators/blob/5187948c67b07cacdcc2ab89145a903bdb80263e/Semantic%20Scholar.js#L117-L122). 

But the bibtex exporter is then ignoring this attachment, see https://github.com/zotero/translators/blob/5187948c67b07cacdcc2ab89145a903bdb80263e/BibTeX.js#L1543-L1563. And honestly, I also don't know where such a url would be best saved. The `url` field would be best used for the canonical url at the journal, and not researchgate. 

So why do you need the researchgate url in the first place?

**Comment by the-dino-girl** [comment]
I think I understand it now. Unfortunately I'm not a developer and I can't look at the codes :-)

I just finish my jabref library with URL and PDF file for all entries and I saw this one was missing. But I now just use the academia url. I hope you understand what my problem was. 
So whenever I find another paper, I just find the correct url and use that one :)

You can close this issue!
