### ISSUE TITLE
jabRef failed to retrieve metadata

### ISSUE THREAD

**Issue by Sergio-Sclovich** [JabRef/JabRef-Browser-Extension#602]
File at path "/Applications/JabRef.app/Contents/Resources/jabrefHost.py" does not exist, or is not executable 2 Subprocess.sys.mjs:144
    call resource://gre/modules/Subprocess.sys.mjs:144

**Comment by tobiasdiez** [comment]
Without more details I cannot help. This particular error has been also reported before, see eg https://github.com/JabRef/JabRef-Browser-Extension/issues/390 and others for potential workarounds.
