### ISSUE TITLE
Wrong path in org.jabref.jabref.json File

### ISSUE THREAD

**Issue by lassestahnke** [JabRef/JabRef-Browser-Extension#605]
Hi, 
I have encountered an issue with the browser extension for Firefox on Mac. The [**org.jabref.jabref.json**](https://raw.githubusercontent.com/JabRef/jabref/main/buildres/mac/native-messaging-host/firefox/org.jabref.jabref.json) file that is linked on [Browser Extension](https://docs.jabref.org/collect/jabref-browser-extension#installation-and-configuration) is missing "/Resources/" in the path entry. 

The Json file should look like this:
 {
  "name": "org.jabref.jabref",
  "description": "JabRef",
  "path": "/Applications/JabRef.app/Contents/Resources/jabrefHost.py",
  "type": "stdio",
  "allowed_extensions": ["browserextension@jabref.org", "@jabfox"]
}

The extension throws an error with the currently provided file.

```[tasklist]
### Tasks
```

**Comment by Siedlerchr** [comment]
This was changed in jabref 5.11 or 5.12. Please use the pkg installer to install the new version as it will take care of the browser extension
