### ISSUE TITLE
The browser extension does not work: Error connecting to JabRef

### ISSUE THREAD

**Issue by wasaCheney** [JabRef/JabRef-Browser-Extension#611]
I am in Fedora 40, and installed JabRef, Chrome, and Edge by Flatpak.
Then follow the manual steps via [jabref browser extension](https://docs.jabref.org/collect/jabref-browser-extension),
but the extention always giveback the "Error connecting to JabRef" as the img shows,

![image](https://github.com/JabRef/JabRef-Browser-Extension/assets/18375090/6766298a-bb6f-4dd5-958c-bd08f6812806)

I also checked other similar issues, but no progress.

Could anyone give me some hints? Thx

Ps. The firefox extention worked well several days ago, but now it give the same error -_-

**Comment by wasaCheney** [comment]
Ps. The version info
JabRef 5.13--2024-04-01--6bdcf63

**Comment by LyzardKing** [comment]
I'll look into this.
I have to try to install the extension from scratch and see what happens.

**Comment by LyzardKing** [comment]
@wasaCheney 
With the flatpak it seems to be a bit different. I need to update the manual, and possibly also automate this.

copy the downloaded json file to `~/.var/app/com.google.Chrome/config/google-chrome/NativeMessagingHosts`
and replace the path with `/home/<your username>/.var/app/com.google.Chrome/config/google-chrome/NativeMessagingHosts/jabrefHost.py`

Then you need to copy the .py file, that is contained in the flatpak, by running:
`cp /var/lib/flatpak/app/org.jabref.jabref/current/active/files/lib/jabrefHost.py /home/<your username>/.var/app/com.google.Chrome/config/google-chrome/NativeMessagingHosts/jabrefHost.py`

I'll look into automating this process, but for now it should work.
You would have to do the same with Edge, but the path might be different (should be in the manual installation page)

**Comment by wasaCheney** [comment]
Great! @LyzardKing 
Following your steps makes everything work well! Saves my life！
Thank you very much.

Maybe the issue could be closed
