### ISSUE TITLE
Add proper integration tests and deployment

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/JabRef-Browser-Extension#73]
- Create tests: https://developer.mozilla.org/en-US/docs/Mozilla/QA/Mozmill_tests/Addon_tests

- Deployment:
   - https://alosarjos.gitlab.io/alosarblog/post/continuous-integration-for-a-firefox-extension/
   - probably depends on https://github.com/mozilla/web-ext/issues/804

**Comment by LyzardKing** [comment]
The testing should probably be written with marionette, or directly in the web-ext environment, sincr mozmill is deprecated.
This tool can be used to automatically upload to firefox/chrome/opera stores (once the chrome extension works ;) )
https://github.com/LinusU/wext-shipit

**Comment by tobiasdiez** [comment]
I don't see any way to test the extension in a proper way right now. Especially given that the most problems currently occur at the Extension > JabRef communication step, which is especially hard to automate.
