### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by arshadkazmi42** [JabRef/JabRef-Browser-Extension#76]
Link to jabref.json in Mac-OS installation steps is broken.

Wrong URL:  https://github.com/JabRef/jabref/blob/master/buildres/jabref.json

Correct URL: https://github.com/JabRef/jabref/blob/master/buildres/windows/jabref.json

**Comment by arshadkazmi42** [comment]
I am working on it

**Comment by ericrbg** [comment]
This is also true for the Windows custom installation.

**Comment by tobiasdiez** [comment]
Should be fixed now.
