### ISSUE TITLE
Error with manifest in Linux

### ISSUE THREAD

**Issue by jorgman1** [JabRef/JabRef-Browser-Extension#88]
When trying to use the extension, I get the following error:

"This extension does not have permission to use native manifest /usr/lib/mozilla/native-messaging-hosts/org.jabref.jabref.json"

I'm using Firefox 70.0.1, and Jabref 5.0.

The file is readable and executable by all.

**Comment by LyzardKing** [comment]
There might be a mismatch between the id in the extension and the manifest..
@tobiasdiez Did you update the firefox extension?
The extension downloadable from mozilla still has id `@jabfox`
but the id in jabref is the new one..
For the meantime @jorgman1 you can change the id in the json file to `@jabfox`, but you will then need to revert back to the value it shows now.

**Comment by tobiasdiez** [comment]
Thanks to @LyzardKing this should be fixed now (if you use the latest dev version). Thanks for the report!
