### ISSUE TITLE
[Linux] Must change json in order to work

### ISSUE THREAD

**Issue by diabl0w** [JabRef/JabRef-Browser-Extension#89]
Currently on linux, we must change the "allowed-extensions" line in the json file from native-messaging-hosts from "browserextension@jabref.org" to "@jabfox"

**Comment by tobiasdiez** [comment]
I cannot publish the update of the add-on that contains the rename to the Firefox store as this would require people to upgrade to JabRef 5 (which is not yet released).

@LyzardKing I think we need revert the rename (in the json file) until 5.0 is almost ready to be released. What do you think?

**Comment by LyzardKing** [comment]
Or add more than one in the JSON...I think it's supported...we should be able to easily test it
That way we can enable both the dev and the stable versions...

**Comment by tobiasdiez** [comment]
Oh, that's a great idea! Do you have time to test it? I'm currently on travel and busy until next week...

**Comment by tobiasdiez** [comment]
Thanks to @LyzardKing this should be fixed now (if you use the latest dev version). Thanks for the report!
