### ISSUE TITLE
Stuck on Searching for Bibliographic Data, Errors saying to update code

### ISSUE THREAD

**Issue by diabl0w** [JabRef/JabRef-Browser-Extension#91]
URL tested: https://www.ahajournals.org/doi/full/10.1161/atvbaha.110.221101

Console Debug:

`JabFox: Popup opened progressPanel.js:10:10
Messaging: Received message: undefined, undefined messaging.js:53:11
JabFox: Popup opened confirmed background.js:121:11
TypeError: messageName is undefined at moz-extension://8aa0ebb4-5345-42a5-a923-853ee8a31e7c/Zotero/messaging.js:63 zotero.js:284:12
JabFox: Start translation for tab  
Object { id: 5, index: 4, windowId: 1, highlighted: true, active: true, attention: false, pinned: false, status: "complete", hidden: false, discarded: false, … }
background.js:130:13
Messaging: Received message: Debug.log, translate message received in injected page https://www.ahajournals.org/doi/full/10.1161/atvbaha.110.221101, messaging.js:53:11
(3)(+0027483): translate message received in injected page https://www.ahajournals.org/doi/full/10.1161/atvbaha.110.221101 debug.js:171:20
Messaging: Received message: Prefs.getAsync, firstSaveToServer messaging.js:53:11
Messaging: Received message: Connector.checkIsOnline, messaging.js:53:11
Messaging: Received message: Messaging.sendMessage, progressWindow.show, messaging.js:53:11
Messaging: Received message: Debug.log, Translate: Parsing code for Atypon Journals (5af42734-7cd5-4c69-97fc-bc406999bdba, 2018-04-21 06:20:00),4 messaging.js:53:11
(4)(+0000040): Translate: Parsing code for Atypon Journals (5af42734-7cd5-4c69-97fc-bc406999bdba, 2018-04-21 06:20:00) debug.js:171:20
Messaging: Received message: undefined, undefined messaging.js:53:11
TypeError: messageName is undefined at moz-extension://8aa0ebb4-5345-42a5-a923-853ee8a31e7c/Zotero/messaging.js:63 zotero.js:284:12
Messaging: Received message: Debug.log, progressWindow.show message received in injected page https://www.ahajournals.org/doi/full/10.1161/atvbaha.110.221101, messaging.js:53:11
(3)(+0000005): progressWindow.show message received in injected page https://www.ahajournals.org/doi/full/10.1161/atvbaha.110.221101 debug.js:171:20
Messaging: Received message: Connector.callMethod, getSelectedCollection,[object Object] messaging.js:53:11
JabFox: Tried to contact Zotero standalone: getSelectedCollection connector.js:3:11
Error: Zotero Offline at moz-extension://8aa0ebb4-5345-42a5-a923-853ee8a31e7c/connector.js:4 zotero.js:284:12
JabFox: code executed background.js:87:22
Messaging: Received message: Debug.log, Translate: Beginning translation with Atypon Journals, messaging.js:53:11
(3)(+0000005): Translate: Beginning translation with Atypon Journals debug.js:171:20
Messaging: Received message: Debug.log, Translate: Citation URL: https://www.ahajournals.org/action/showCitFormats?doi=10.1161/atvbaha.110.221101, messaging.js:53:11
(3)(+0000005): Translate: Citation URL: https://www.ahajournals.org/action/showCitFormats?doi=10.1161/atvbaha.110.221101 debug.js:171:20
Messaging: Received message: Debug.log, Translate: resolving URL https://www.ahajournals.org/action/showCitFormats?doi=10.1161/atvbaha.110.221101, messaging.js:53:11
(3)(+0000002): Translate: resolving URL https://www.ahajournals.org/action/showCitFormats?doi=10.1161/atvbaha.110.221101 debug.js:171:20
Messaging: Received message: Debug.log, Translate: resolved to https://www.ahajournals.org/action/showCitFormats?doi=10.1161/atvbaha.110.221101, messaging.js:53:11
(3)(+0000002): Translate: resolved to https://www.ahajournals.org/action/showCitFormats?doi=10.1161/atvbaha.110.221101 debug.js:171:20
Messaging: Received message: Debug.log, Zotero.HTTP.processDocuments() now takes only 2 arguments -- update your code, messaging.js:53:11
(3)(+0000000): Zotero.HTTP.processDocuments() now takes only 2 arguments -- update your code debug.js:171:20
Messaging: Received message: Debug.log, HTTP GET https://www.ahajournals.org/action/showCitFormats?doi=10.1161/atvbaha.110.221101, messaging.js:53:11
(3)(+0000001): HTTP GET https://www.ahajournals.org/action/showCitFormats?doi=10.1161/atvbaha.110.221101 debug.js:171:20
ReferenceError: require is not defined at moz-extension://8aa0ebb4-5345-42a5-a923-853ee8a31e7c/Zotero/http.js:233 zotero.js:284:12
Messaging: Received message: Errors.log, require is not defined
Zotero.HTTP</this.wrapDocument@moz-extension://8aa0ebb4-5345-42a5-a923-853ee8a31e7c/Zotero/http.js:233:13
Zotero.HTTP.processDocuments/funcs</</<@moz-extension://8aa0ebb4-5345-42a5-a923-853ee8a31e7c/Zotero/http_inject.js:83:27
messaging.js:53:11
Messaging: Received message: Debug.log, Translate: Translation using Atypon Journals failed: 
ReferenceError: require is not defined

Zotero.HTTP</this.wrapDocument@moz-extension://8aa0ebb4-5345-42a5-a923-853ee8a31e7c/Zotero/http.js:233:13
Zotero.HTTP.processDocuments/funcs</</<@moz-extension://8aa0ebb4-5345-42a5-a923-853ee8a31e7c/Zotero/http_inject.js:83:27

url => https://www.ahajournals.org/doi/full/10.1161/atvbaha.110.221101
downloadAssociatedFiles => true
automaticSnapshots => true,2 messaging.js:53:11
ReferenceError: require is not defined http.js:233:13
(2)(+0000546): Translate: Translation using Atypon Journals failed: 
ReferenceError: require is not defined

Zotero.HTTP</this.wrapDocument@moz-extension://8aa0ebb4-5345-42a5-a923-853ee8a31e7c/Zotero/http.js:233:13
Zotero.HTTP.processDocuments/funcs</</<@moz-extension://8aa0ebb4-5345-42a5-a923-853ee8a31e7c/Zotero/http_inject.js:83:27

url => https://www.ahajournals.org/doi/full/10.1161/atvbaha.110.221101
downloadAssociatedFiles => true
automaticSnapshots => true debug.js:171:20
Messaging: Received message: Debug.log, Translate: Running handler 0 for error,5 messaging.js:53:11
(5)(+0000003): Translate: Running handler 0 for error debug.js:171:20
Messaging: Received message: Prefs.getAsync, reportTranslationFailure messaging.js:53:11
Messaging: Received message: Messaging.sendMessage, progressWindow.done,false messaging.js:53:11
Messaging: Received message: Debug.log, progressWindow.done message received in injected page https://www.ahajournals.org/doi/full/10.1161/atvbaha.110.221101, messaging.js:53:11
(3)(+0000012): progressWindow.done message received in injected page https://www.ahajournals.org/doi/full/10.1161/atvbaha.110.221101 debug.js:171:20
`

Not sure exactly what is going on, but `Zotero.HTTP.processDocuments() now takes only 2 arguments -- update your code debug.js:171:20` seems like it may be an issue along with the many  `require is not defined` errors

**Comment by diabl0w** [comment]
to save you some time, the first "require is not defined" error that we get, which is in line 133 of http.js, that line is `let url = require('url')`

**Comment by diabl0w** [comment]
so, i believe that "require is not defined errors" are caused by the "Zotero.HTTP.processDocuments()" error which I believe is caused by lines 256-267 of utilities_translate.js which gives 3 arguments to processDocuments

this is all just me guessing, to try and help and get this solved quicker, as i am not a programmer

**Comment by tobiasdiez** [comment]
This should be fixed in the next release.
