### ISSUE TITLE
Stuck on Searching for Bibliographic Data, Different Error

### ISSUE THREAD

**Issue by diabl0w** [JabRef/JabRef-Browser-Extension#92]
Another very basic and common website

URL: https://sci-hub.se/https%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fpmc%2Farticles%2FPMC3123451%2F

Log:

uncaught exception: Object 15
JabFox: Searching for translators for  
Object { id: 19, index: 7, windowId: 1, highlighted: true, active: true, attention: false, pinned: false, status: "loading", hidden: false, discarded: false, … }
background.js:68:10
(3)(+0052201): Translators: Looking for translators for https://sci-hub.se/https%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fpmc%2Farticles%2FPMC3123451%2F debug.js:171:20
JabFox: Found potential translators  
Array(4) [ {…}, {…}, {…}, {…} ]
background.js:77:12
Messaging: Received message: Prefs.getAll, 2 messaging.js:53:11
LoginManager: searchLogins: `formActionOrigin` or `httpRealm` is recommended LoginManager.jsm:473:13
Rejected untrusted message from https://sci-hub.se viewer.js:11439:17
Messaging: Received message: Translators.getWebTranslatorsForLocation, https://sci-hub.se/https%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fpmc%2Farticles%2FPMC3123451%2F,https://sci-hub.se/https%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fpmc%2Farticles%2FPMC3123451%2F messaging.js:53:11
(3)(+0000869): Translators: Looking for translators for https://sci-hub.se/https%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fpmc%2Farticles%2FPMC3123451%2F debug.js:171:20
Messaging: Received message: Debug.log, Translate: Binding sandbox to https://sci-hub.se/https%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fpmc%2Farticles%2FPMC3123451%2F,4 messaging.js:53:11
(4)(+0000025): Translate: Binding sandbox to https://sci-hub.se/https%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fpmc%2Farticles%2FPMC3123451%2F debug.js:171:20
Messaging: Received message: undefined, undefined messaging.js:53:11
TypeError: messageName is undefined at moz-extension://e64d880e-e9a8-4941-8c3a-98a3a3e46fa6/Zotero/messaging.js:63 zotero.js:284:12
Messaging: Received message: Debug.log, Translate: Parsing code for unAPI (e7e01cac-1e37-4da6-b078-a0e8343b0e98, 2019-07-15 19:40:00),4 messaging.js:53:11
(4)(+0000009): Translate: Parsing code for unAPI (e7e01cac-1e37-4da6-b078-a0e8343b0e98, 2019-07-15 19:40:00) debug.js:171:20
Messaging: Received message: undefined, undefined messaging.js:53:11
TypeError: messageName is undefined at moz-extension://e64d880e-e9a8-4941-8c3a-98a3a3e46fa6/Zotero/messaging.js:63 zotero.js:284:12
JabFox: code executed 2 background.js:87:22
Messaging: Received message: Prefs.getAsync, reportTranslationFailure messaging.js:53:11
Messaging: Received message: Debug.log, Translate: Parsing code for COinS (05d07af9-105a-4572-99f6-a8e231c0daef, 2015-06-04 03:30:00),4 messaging.js:53:11
(4)(+0000042): Translate: Parsing code for COinS (05d07af9-105a-4572-99f6-a8e231c0daef, 2015-06-04 03:30:00) debug.js:171:20
Messaging: Received message: undefined, undefined messaging.js:53:11
TypeError: messageName is undefined at moz-extension://e64d880e-e9a8-4941-8c3a-98a3a3e46fa6/Zotero/messaging.js:63 zotero.js:284:12
JabFox: code executed background.js:87:22
Messaging: Received message: Prefs.getAsync, reportTranslationFailure messaging.js:53:11
Request to access cookie or storage on “<URL>” was blocked because it came from a tracker  2
Messaging: Received message: Debug.log, Translate: Parsing code for Embedded Metadata (951c027d-74ac-47d4-a107-9c3069ab7b48, 2018-11-01 23:10:00),4 messaging.js:53:11
(4)(+0000017): Translate: Parsing code for Embedded Metadata (951c027d-74ac-47d4-a107-9c3069ab7b48, 2018-11-01 23:10:00) debug.js:171:20
Messaging: Received message: undefined, undefined messaging.js:53:11
TypeError: messageName is undefined at moz-extension://e64d880e-e9a8-4941-8c3a-98a3a3e46fa6/Zotero/messaging.js:63 zotero.js:284:12
JabFox: code executed background.js:87:22
Messaging: Received message: Debug.log, Translate: Embedded Metadata: found 2 meta tags., messaging.js:53:11
(3)(+0000024): Translate: Embedded Metadata: found 2 meta tags. debug.js:171:20
Messaging: Received message: Prefs.getAsync, reportTranslationFailure messaging.js:53:11
Messaging: Received message: Debug.log, Translate: Parsing code for DOI (c159dcfe-8a53-4301-a499-30f6549c340d, 2019-04-07 02:15:00),4 messaging.js:53:11
(4)(+0000008): Translate: Parsing code for DOI (c159dcfe-8a53-4301-a499-30f6549c340d, 2019-04-07 02:15:00) debug.js:171:20
Messaging: Received message: undefined, undefined messaging.js:53:11
TypeError: messageName is undefined at moz-extension://e64d880e-e9a8-4941-8c3a-98a3a3e46fa6/Zotero/messaging.js:63 zotero.js:284:12
JabFox: code executed background.js:87:22
Messaging: Received message: Debug.log, Translate: All translator detect calls and RPC calls complete:, messaging.js:53:11
(3)(+0000067): Translate: All translator detect calls and RPC calls complete: debug.js:171:20
Messaging: Received message: Debug.log, 	DOI: 400, messaging.js:53:11
(3)(+0000003): 	DOI: 400 debug.js:171:20
PDF 444913a60978233573e51c8b3a4d26c4 [1.4 - / XPP] (PDF.js: 2.3.101) viewer.js:1228:15
Messaging: Received message: Debug.log, Translate: Running handler 0 for translators,5 messaging.js:53:11
(5)(+0000004): Translate: Running handler 0 for translators debug.js:171:20
Messaging: Received message: Prefs.getAsync, reportTranslationFailure messaging.js:53:11
Invalid string label
Messaging: Received message: Connector_Browser.onTranslators, [object Object],0,text/html messaging.js:53:11
JabFox: Found translators  
Array [ {…} ]
  for tab  
Object { id: 19, index: 7, windowId: 1, highlighted: true, active: true, attention: false, pinned: false, status: "complete", hidden: false, discarded: false, … }
background.js:107:13
JabFox: Popup opened progressPanel.js:10:10
Messaging: Received message: undefined, undefined messaging.js:53:11
JabFox: Popup opened confirmed background.js:121:11
TypeError: messageName is undefined at moz-extension://e64d880e-e9a8-4941-8c3a-98a3a3e46fa6/Zotero/messaging.js:63 zotero.js:284:12
JabFox: Start translation for tab  
Object { id: 19, index: 7, windowId: 1, highlighted: true, active: true, attention: false, pinned: false, status: "complete", hidden: false, discarded: false, … }
background.js:130:13
Messaging: Received message: Debug.log, translate message received in injected page https://sci-hub.se/https%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fpmc%2Farticles%2FPMC3123451%2F, messaging.js:53:11
(3)(+0006754): translate message received in injected page https://sci-hub.se/https%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fpmc%2Farticles%2FPMC3123451%2F debug.js:171:20
Messaging: Received message: Prefs.getAsync, firstSaveToServer messaging.js:53:11
Messaging: Received message: Connector.checkIsOnline, messaging.js:53:11
Messaging: Received message: Messaging.sendMessage, progressWindow.show, messaging.js:53:11
Messaging: Received message: Debug.log, Translate: Parsing code for DOI (c159dcfe-8a53-4301-a499-30f6549c340d, 2019-04-07 02:15:00),4 messaging.js:53:11
(4)(+0000230): Translate: Parsing code for DOI (c159dcfe-8a53-4301-a499-30f6549c340d, 2019-04-07 02:15:00) debug.js:171:20
Messaging: Received message: undefined, undefined messaging.js:53:11
TypeError: messageName is undefined at moz-extension://e64d880e-e9a8-4941-8c3a-98a3a3e46fa6/Zotero/messaging.js:63 zotero.js:284:12
Messaging: Received message: Debug.log, progressWindow.show message received in injected page https://sci-hub.se/https%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fpmc%2Farticles%2FPMC3123451%2F, messaging.js:53:11
(3)(+0000020): progressWindow.show message received in injected page https://sci-hub.se/https%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fpmc%2Farticles%2FPMC3123451%2F debug.js:171:20
Messaging: Received message: Connector.callMethod, getSelectedCollection,[object Object] messaging.js:53:11
JabFox: Tried to contact Zotero standalone: getSelectedCollection connector.js:3:11
Error: Zotero Offline at moz-extension://e64d880e-e9a8-4941-8c3a-98a3a3e46fa6/connector.js:4 zotero.js:284:12
JabFox: code executed background.js:87:22
Messaging: Received message: Debug.log, Translate: Beginning translation with DOI, messaging.js:53:11
(3)(+0000022): Translate: Beginning translation with DOI debug.js:171:20
Messaging: Received message: Debug.log, 10.1161/ATVBAHA.110.221101,10.1161/atvbaha.110.221101, messaging.js:53:11
(3)(+0000009): [
    "0": "10.1161/ATVBAHA.110.221101"
    "1": "10.1161/atvbaha.110.221101"
] debug.js:171:20
Messaging: Received message: Debug.log, Translate: Creating translate instance of type search in sandbox, messaging.js:53:11
(3)(+0000009): Translate: Creating translate instance of type search in sandbox debug.js:171:20
Messaging: Received message: Translators.get, b28d0d42-8549-4c6d-83fc-8382874a5cb9 messaging.js:53:11
Messaging: Received message: Debug.log, Translate: Creating translate instance of type search in sandbox, messaging.js:53:11
(3)(+0000018): Translate: Creating translate instance of type search in sandbox debug.js:171:20
Messaging: Received message: Translators.get, b28d0d42-8549-4c6d-83fc-8382874a5cb9 messaging.js:53:11
Messaging: Received message: Debug.log, Translate: Binding sandbox to https://sci-hub.se/https%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fpmc%2Farticles%2FPMC3123451%2F,4 messaging.js:53:11
(4)(+0000072): Translate: Binding sandbox to https://sci-hub.se/https%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fpmc%2Farticles%2FPMC3123451%2F debug.js:171:20
Messaging: Received message: undefined, undefined messaging.js:53:11
TypeError: messageName is undefined at moz-extension://e64d880e-e9a8-4941-8c3a-98a3a3e46fa6/Zotero/messaging.js:63 zotero.js:284:12
Messaging: Received message: Debug.log, Translate: Parsing code for DOI Content Negotiation (b28d0d42-8549-4c6d-83fc-8382874a5cb9, 2019-04-07 02:15:00),4 messaging.js:53:11
(4)(+0000014): Translate: Parsing code for DOI Content Negotiation (b28d0d42-8549-4c6d-83fc-8382874a5cb9, 2019-04-07 02:15:00) debug.js:171:20
Messaging: Received message: undefined, undefined messaging.js:53:11
TypeError: messageName is undefined at moz-extension://e64d880e-e9a8-4941-8c3a-98a3a3e46fa6/Zotero/messaging.js:63 zotero.js:284:12
Messaging: Received message: Debug.log, Translate: Binding sandbox to https://sci-hub.se/https%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fpmc%2Farticles%2FPMC3123451%2F,4 messaging.js:53:11
(4)(+0000014): Translate: Binding sandbox to https://sci-hub.se/https%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fpmc%2Farticles%2FPMC3123451%2F debug.js:171:20
Messaging: Received message: undefined, undefined messaging.js:53:11
TypeError: messageName is undefined at moz-extension://e64d880e-e9a8-4941-8c3a-98a3a3e46fa6/Zotero/messaging.js:63 zotero.js:284:12
Messaging: Received message: Debug.log, Translate: Parsing code for DOI Content Negotiation (b28d0d42-8549-4c6d-83fc-8382874a5cb9, 2019-04-07 02:15:00),4 messaging.js:53:11
(4)(+0000014): Translate: Parsing code for DOI Content Negotiation (b28d0d42-8549-4c6d-83fc-8382874a5cb9, 2019-04-07 02:15:00) debug.js:171:20
Messaging: Received message: undefined, undefined messaging.js:53:11
TypeError: messageName is undefined at moz-extension://e64d880e-e9a8-4941-8c3a-98a3a3e46fa6/Zotero/messaging.js:63 zotero.js:284:12
JabFox: code executed 2 background.js:87:22
TypeError: this._translatorInfo is undefined translate.js:1368:30
JabFox: code executed 2 background.js:87:22
Messaging: Received message: Debug.log, Translate: Beginning translation with DOI Content Negotiation, messaging.js:53:11
(3)(+0000116): Translate: Beginning translation with DOI Content Negotiation debug.js:171:20
Messaging: Received message: Debug.log, Translate: resolving URL https://doi.org/10.1161%2Fatvbaha.110.221101, messaging.js:53:11
(3)(+0000003): Translate: resolving URL https://doi.org/10.1161%2Fatvbaha.110.221101 debug.js:171:20
Messaging: Received message: Debug.log, Translate: resolved to https://doi.org/10.1161%2Fatvbaha.110.221101, messaging.js:53:11
(3)(+0000004): Translate: resolved to https://doi.org/10.1161%2Fatvbaha.110.221101 debug.js:171:20
Messaging: Received message: Debug.log, Zotero.HTTP.doGet is deprecated. Use Zotero.HTTP.request, messaging.js:53:11
(3)(+0000005): Zotero.HTTP.doGet is deprecated. Use Zotero.HTTP.request debug.js:171:20
Messaging: Received message: Debug.log, HTTP GET https://doi.org/10.1161%2Fatvbaha.110.221101, messaging.js:53:11
(3)(+0000005): HTTP GET https://doi.org/10.1161%2Fatvbaha.110.221101 debug.js:171:20
Exception { name: "NS_ERROR_NOT_AVAILABLE", message: "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsICacheInfoChannel.isRacing]", result: 2147746065, filename: "resource://devtools/server/actors/network-monitor/network-response-listener.js", lineNumber: 335, columnNumber: 0, data: null, stack: "NetworkResponseListener.prototype._getSecurityInfo<@resource://devtools/server/actors/network-monitor/network-response-listener.js:335:26\nexports.makeInfallible/<@resource://devtools/shared/ThreadSafeDevToolsUtils.js:111:22\nonStartRequest@resource://devtools/server/actors/network-monitor/network-response-listener.js:224:10\n", location: XPCWrappedNative_NoHelper }
ThreadSafeDevToolsUtils.js:90:13
Messaging: Received message: Debug.log, Translate: <?xml version="1.0" encoding="UTF-8"?>
<doi_records>

  <doi_record owner="10.1161" timestamp="2019-06-11 15:50:37">

    <crossref>

      <journal>

        <journal_metadata language="en">

          <full_title>Arteriosclerosis, Thrombosis, and Vascular Biology</full_title>

          <abbrev_title>Arterioscler Thromb Vasc Biol.</abbrev_title>

          <issn media_type="print">1079-5642</issn>

          <issn media_type="electronic">1524-4636</issn>

        </journal_metadata>

        <journal_issue>

          <publication_date media_type="print">

            <month>07</month>

            <year>2011</year>

          </publication_date>

          <journal_volume>

            <volume>31</volume>

          </journal_volume>

          <issue>7</issue>

        </journal_issue>

        <journal_article publication_type="full_text">

          <titles>

            <title>Smooth Muscle Cell Differentiation In Vitro</title>
…
messaging.js:53:11
(3)(+0000262): Translate: <?xml version="1.0" encoding="UTF-8"?>
<doi_records>

  <doi_record owner="10.1161" timestamp="2019-06-11 15:50:37">

    <crossref>

      <journal>

        <journal_metadata language="en">

          <full_title>Arteriosclerosis, Thrombosis, and Vascular Biology</full_title>

          <abbrev_title>Arterioscler Thromb Vasc Biol.</abbrev_title>

          <issn media_type="print">1079-5642</issn>

          <issn media_type="electronic">1524-4636</issn>

        </journal_metadata>

        <journal_issue>

          <publication_date media_type="print">

            <month>07</month>

            <year>2011</year>

          </publication_date>

          <journal_volume>

            <volume>31</volume>

          </journal_volume>

          <issue>7</issue>

        </journal_issue>

        <journal_article publication_type="full_text">

          <titles>

            <title>Smooth Muscle Cell Differentiation In Vitro</title>

            <subtitle>Mo…
debug.js:171:20
Messaging: Received message: Debug.log, Translate: Creating translate instance of type import in sandbox, messaging.js:53:11
(3)(+0000074): Translate: Creating translate instance of type import in sandbox debug.js:171:20
Messaging: Received message: Translators.get, 93514073-b541-4e02-9180-c36d2f3bb401 messaging.js:53:11
Messaging: Received message: Debug.log, Translate: Binding sandbox to https://sci-hub.se/https%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fpmc%2Farticles%2FPMC3123451%2F,4 messaging.js:53:11
(4)(+0000166): Translate: Binding sandbox to https://sci-hub.se/https%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fpmc%2Farticles%2FPMC3123451%2F debug.js:171:20
Messaging: Received message: undefined, undefined messaging.js:53:11
TypeError: messageName is undefined at moz-extension://e64d880e-e9a8-4941-8c3a-98a3a3e46fa6/Zotero/messaging.js:63 zotero.js:284:12
Messaging: Received message: Debug.log, Translate: Parsing code for Crossref Unixref XML (93514073-b541-4e02-9180-c36d2f3bb401, 2019-04-28 02:35:00),4 messaging.js:53:11
(4)(+0000019): Translate: Parsing code for Crossref Unixref XML (93514073-b541-4e02-9180-c36d2f3bb401, 2019-04-28 02:35:00) debug.js:171:20
Messaging: Received message: undefined, undefined messaging.js:53:11
TypeError: messageName is undefined at moz-extension://e64d880e-e9a8-4941-8c3a-98a3a3e46fa6/Zotero/messaging.js:63 zotero.js:284:12
JabFox: code executed 2 background.js:87:22
Messaging: Received message: Debug.log, Translate: Beginning translation with Crossref Unixref XML, messaging.js:53:11
(3)(+0000205): Translate: Beginning translation with Crossref Unixref XML debug.js:171:20
Messaging: Received message: Debug.log, Translate: Promise not available in sandbox in _itemDone(), messaging.js:53:11
(3)(+0000039): Translate: Promise not available in sandbox in _itemDone() debug.js:171:20
Messaging: Received message: Debug.log, Translate: Saving item, messaging.js:53:11
(3)(+0000003): Translate: Saving item debug.js:171:20
Messaging: Received message: Debug.log, Translate: Running handler 0 for itemDone,5 messaging.js:53:11
(5)(+0000003): Translate: Running handler 0 for itemDone debug.js:171:20
Messaging: Received message: Debug.log, Translate: Promise not available in sandbox in _itemDone(), messaging.js:53:11
(3)(+0000005): Translate: Promise not available in sandbox in _itemDone() debug.js:171:20
Messaging: Received message: Debug.log, Translate: Saving item, messaging.js:53:11
(3)(+0000004): Translate: Saving item debug.js:171:20
Messaging: Received message: Debug.log, Translate: Running handler 0 for itemDone,5 messaging.js:53:11
(5)(+0000003): Translate: Running handler 0 for itemDone debug.js:171:20
Messaging: Received message: Debug.log, Translate: Translation successful, messaging.js:53:11
(3)(+0000004): Translate: Translation successful debug.js:171:20
Messaging: Received message: Debug.log, Translate: Running handler 0 for done,5 messaging.js:53:11
(5)(+0000003): Translate: Running handler 0 for done debug.js:171:20
Messaging: Received message: Debug.log, Translate: Running handler 1 for done,5 messaging.js:53:11
(5)(+0000004): Translate: Running handler 1 for done debug.js:171:20
Messaging: Received message: Debug.log, Translate: Translation successful, messaging.js:53:11
(3)(+0000004): Translate: Translation successful debug.js:171:20
Messaging: Received message: Debug.log, Translate: Running handler 0 for done,5 messaging.js:53:11
(5)(+0000003): Translate: Running handler 0 for done debug.js:171:20
Messaging: Received message: Debug.log, Translate: Running handler 1 for done,5 messaging.js:53:11
(5)(+0000004): Translate: Running handler 1 for done debug.js:171:20
Messaging: Received message: Debug.log, Translate: Running handler 2 for done,5 messaging.js:53:11
(5)(+0000004): Translate: Running handler 2 for done debug.js:171:20

I apologize, but I am not sure I understand how others are using this addon. Perhaps I am doing something wrong, can anyone help? I have only had it work for me once out of 8 different articles I wanted. Zotero was able to get 8/8 and automatically download full text files for 7/8

**Comment by tobiasdiez** [comment]
Thanks for reporting these issues. Linux support is still pretty new (about one or two weeks) and thus somewhat experimental.

**Comment by diabl0w** [comment]
> Thanks for reporting these issues. Linux support is still pretty new (about one or two weeks) and thus somewhat experimental.

I am new to this repo, so thanks for the heads up. Thanks for supporting Linux!

**Comment by diabl0w** [comment]
I think this issue can now be closed, as its working now... can anyone else confirm?

**Comment by tobiasdiez** [comment]
Thanks for the feedback. If the issue should reappear, feel free to open this issue again!
