### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by jorgman1** [JabRef/JabRef-Browser-Extension#93]
Links pointing to files for manual installation are broken. (E.g. https://github.com/JabRef/jabref/blob/master/buildres/jabref.json)

**Comment by LyzardKing** [comment]
This is the correct link:
https://github.com/JabRef/jabref/blob/master/buildres/windows/jabref.json

**Comment by jorgman1** [comment]
Thank you

**Comment by jorgman1** [comment]
Duplicate on #76
