### ISSUE TITLE
Windows: No such native application org.jabref.jabref

### ISSUE THREAD

**Issue by jorgman1** [JabRef/JabRef-Browser-Extension#94]
I get the following error with the latest JabRef-build (2019-11-15) in Windows (win-7x64)

`No such native application org.jabref.jabref
    startupPromise resource://gre/modules/NativeMessaging.jsm:114`

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by jorgman1** [comment]
Sorry for the delay. I had some troubles with the new .msi file. It works fine now!
