### ISSUE TITLE
Stuck on "Send to JabRef"

### ISSUE THREAD

**Issue by jorgman1** [JabRef/JabRef-Browser-Extension#99]
I get the following error.
Firefox: 70.0.1
Extension: 2.1.2 (Last updated 2019-11-19)
JabRef: 5.0.0 (2019-11-19)
OS: Linux Mint 18.1

> stderr output from native app org.jabref.jabref:   File "/opt/jabref/lib/jabrefHost.py", line 34
>stderr output from native app org.jabref.jabref:     logging.info(f"Got length: {message_length} bytes to be read")
>stderr output from native app org.jabref.jabref:                                                                 ^
>stderr output from native app org.jabref.jabref: SyntaxError: invalid syntax
>stderr output from native app org.jabref.jabref: Error in sys.excepthook:
>stderr output from native app org.jabref.jabref: Traceback (most recent call last):
>stderr output from native app org.jabref.jabref:   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
>stderr output from native app org.jabref.jabref:     os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
>stderr output from native app org.jabref.jabref: FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_opt_jabref_lib_jabrefHost.py.1001.crash'
>stderr output from native app org.jabref.jabref: 
>stderr output from native app org.jabref.jabref: Original exception was:
>stderr output from native app org.jabref.jabref:   File "/opt/jabref/lib/jabrefHost.py", line 34
>stderr output from native app org.jabref.jabref:     logging.info(f"Got length: {message_length} bytes to be read")
>stderr output from native app org.jabref.jabref:                                                                 ^
>stderr output from native app org.jabref.jabref: SyntaxError: invalid syntax

**Comment by tobiasdiez** [comment]
@LyzardKing can you have a look at this please. Seems to be related to your recent changes.

**Comment by LyzardKing** [comment]
I can't replicate, but the issue might be that Linux Mint uses an older version of Python3 that doesn't have support for fstrings..
If that's the case we might need to revert that change.
I'll look into it today and determine if that is the issue

**Comment by LyzardKing** [comment]
It is a release from 2016-12-16, so that might in fact be the issue

**Comment by LyzardKing** [comment]
@jorgman1 I uploaded a branch with a possible fix.
You can test it from https://builds.jabref.org/removeFstring/

**Comment by jorgman1** [comment]
@LyzardKing: I get the following error now:
(I'm using Python 3.5.2)

>stderr output from native app org.jabref.jabref: Traceback (most recent call last):
>stderr output from native app org.jabref.jabref:   File "/opt/jabref/lib/jabrefHost.py", line 25, in <module>
>stderr output from native app org.jabref.jabref:     logging.basicConfig(filename=logging_dir / "jabref_browser_extension.log")
>stderr output from native app org.jabref.jabref:   File "/usr/lib/python3.5/logging/__init__.py", line 1744, in basicConfig
>stderr output from native app org.jabref.jabref:     h = FileHandler(filename, mode)
>stderr output from native app org.jabref.jabref:   File "/usr/lib/python3.5/logging/__init__.py", line 998, in __init__
>stderr output from native app org.jabref.jabref:     self.baseFilename = os.path.abspath(filename)
>stderr output from native app org.jabref.jabref:   File "/usr/lib/python3.5/posixpath.py", line 357, in abspath
>stderr output from native app org.jabref.jabref:     if not isabs(path):
>stderr output from native app org.jabref.jabref:   File "/usr/lib/python3.5/posixpath.py", line 64, in isabs
>stderr output from native app org.jabref.jabref:     return s.startswith(sep)
>stderr output from native app org.jabref.jabref: AttributeError: 'PosixPath' object has no attribute 'startswith'
>stderr output from native app org.jabref.jabref: Error in sys.excepthook:
>stderr output from native app org.jabref.jabref: Traceback (most recent call last):
>stderr output from native app org.jabref.jabref:   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
>stderr output from native app org.jabref.jabref:     os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
>stderr output from native app org.jabref.jabref: FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_opt_jabref_lib_jabrefHost.py.1001.crash'
>stderr output from native app org.jabref.jabref: 
>stderr output from native app org.jabref.jabref: Original exception was:
>stderr output from native app org.jabref.jabref: Traceback (most recent call last):
>stderr output from native app org.jabref.jabref:   File "/opt/jabref/lib/jabrefHost.py", line 25, in <module>
>stderr output from native app org.jabref.jabref:     logging.basicConfig(filename=logging_dir / "jabref_browser_extension.log")
>stderr output from native app org.jabref.jabref:   File "/usr/lib/python3.5/logging/__init__.py", line 1744, in basicConfig
>stderr output from native app org.jabref.jabref:     h = FileHandler(filename, mode)
>stderr output from native app org.jabref.jabref:   File "/usr/lib/python3.5/logging/__init__.py", line 998, in __init__
>stderr output from native app org.jabref.jabref:     self.baseFilename = os.path.abspath(filename)
>stderr output from native app org.jabref.jabref:   File "/usr/lib/python3.5/posixpath.py", line 357, in abspath
>stderr output from native app org.jabref.jabref:     if not isabs(path):
>stderr output from native app org.jabref.jabref:   File "/usr/lib/python3.5/posixpath.py", line 64, in isabs
>stderr output from native app org.jabref.jabref:     return s.startswith(sep)
>stderr output from native app org.jabref.jabref: AttributeError: 'PosixPath' object has no attribute 'startswith'

**Comment by LyzardKing** [comment]
This seems to be an issue with the logging module..not with jabref..
https://bugs.python.org/issue27493
I pushed a new commit..as soon as it builds and uploads you can try again and see if it fixes the problems.

**Comment by jorgman1** [comment]
Works like a charm now! Thank you!
What did you change?

**Comment by LyzardKing** [comment]
As noted in the linked url, the versions of the logging module available 
in python3.5 and previous only work with a string as a parameter, not a pathlib object.
So I converted the pathlib object to a string in the logging setup :)
Thank you for testing it!
Now the PR on the main repo can be merged
